// =============================================================================
// PRISMA CLIENT SINGLETON
// =============================================================================
// This file creates a single, reusable Prisma Client instance.
//
// WHY A SINGLETON?
// -----------------
// Next.js uses "hot module reloading" during development - when you save a file,
// it reloads that module. Without this pattern, each reload creates a NEW
// PrismaClient, eventually exhausting database connections (PostgreSQL typically
// allows ~100 concurrent connections).
//
// This pattern stores the client in a global variable that survives hot reloads.
// In production, there's naturally only one instance anyway.
//
// USAGE:
// ------
// import { prisma } from '@/lib/prisma';
//
// // Fetch all species
// const species = await prisma.iCAA.findMany();
//
// // Find species by ID
// const turtle = await prisma.iCAA.findUnique({ where: { ogc_fid: 1 } });
//
// // Get player discoveries with related species data
// const discoveries = await prisma.playerSpeciesDiscovery.findMany({
//   where: { player_id: userId },
//   include: { species: true },
// });
// =============================================================================

import { PrismaClient } from '@prisma/client';

// Type declaration for global namespace to store Prisma instance
// This tells TypeScript that `global.prisma` can exist and is a PrismaClient
const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

/**
 * Shared Prisma Client instance.
 *
 * Features:
 * - Reuses existing client across hot reloads in development
 * - Single instance in production
 * - Minimal logging (errors and warnings only) to keep console clean
 *
 * @example
 * ```typescript
 * import { prisma } from '@/lib/prisma';
 *
 * // Query species catalog
 * const allSpecies = await prisma.iCAA.findMany({
 *   select: { ogc_fid: true, comm_name: true, sci_name: true },
 *   orderBy: { comm_name: 'asc' },
 * });
 * ```
 */
export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    // Configure logging based on environment
    // - Development: Show errors and warnings for debugging
    // - Production: Show only errors to reduce noise
    log:
      process.env.NODE_ENV === 'development'
        ? ['error', 'warn']
        : ['error'],
  });

// In development, store the client in global to reuse across hot reloads
// This prevents the "Too many clients" error
if (process.env.NODE_ENV !== 'production') {
  globalForPrisma.prisma = prisma;
}

// =============================================================================
// TYPE EXPORTS
// =============================================================================
// Re-export commonly used types for convenience.
// These are generated by Prisma from your schema.

export type {
  ICAA,
  Profile,
  PlayerGameSession,
  PlayerSpeciesDiscovery,
  PlayerClueUnlock,
  PlayerStats,
  HabitatColormap,
  OneEarthBioregion,
  HighScore,
} from '@prisma/client';
