/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './app/**/*.{js,ts,jsx,tsx}',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  safelist: [
    'bg-background',
    'bg-card',
    'bg-card/90',
    'bg-secondary',
    'bg-secondary/50',
    'bg-secondary/90',
    'text-foreground',
    'text-muted-foreground',
    'text-secondary-foreground',
    'border-border',
    'border-secondary',
    'text-primary',
    'bg-destructive/10',
    'border-destructive/30',
    'text-destructive',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        /* Design system tokens */
        ds: {
          bg: "var(--ds-background)",
          surface: "var(--ds-surface)",
          "surface-elevated": "var(--ds-surface-elevated)",
          "text-primary": "var(--ds-text-primary)",
          "text-secondary": "var(--ds-text-secondary)",
          "text-muted": "var(--ds-text-muted)",
          cyan: "var(--ds-accent-cyan)",
          amber: "var(--ds-accent-amber)",
          emerald: "var(--ds-accent-emerald)",
          rose: "var(--ds-accent-rose)",
        },
        gem: {
          observe: "var(--ds-gem-observe)",
          scan: "var(--ds-gem-scan)",
          camouflage: "var(--ds-gem-camouflage)",
          traverse: "var(--ds-gem-traverse)",
          pack: "var(--ds-gem-pack)",
          focus: "var(--ds-gem-focus)",
          notes: "var(--ds-gem-notes)",
          burst: "var(--ds-gem-burst)",
        },
      },
      borderColor: {
        "ds-subtle": "var(--ds-border-subtle)",
        "ds-accent": "var(--ds-border-accent)",
      },
      boxShadow: {
        "ds-card": "var(--ds-shadow-card)",
        "glow-cyan": "var(--ds-glow-cyan)",
        "glow-amber": "var(--ds-glow-amber)",
        "glow-rose": "var(--ds-glow-rose)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      spacing: {
        "ds-xs": "4px",
        "ds-sm": "8px",
        "ds-md": "12px",
        "ds-lg": "16px",
        "ds-xl": "24px",
        "safe-top": "47px",
        "safe-bottom": "34px",
        "tab-bar": "56px",
      },
      fontSize: {
        "ds-heading-lg": ["20px", { lineHeight: "1.2", fontWeight: "600" }],
        "ds-heading-sm": ["14px", { lineHeight: "1.3", fontWeight: "600" }],
        "ds-body": ["13px", { lineHeight: "1.4", fontWeight: "400" }],
        "ds-caption": ["11px", { lineHeight: "1.2", fontWeight: "500" }],
        "ds-badge": ["10px", { lineHeight: "1.0", fontWeight: "700", letterSpacing: "0.5px" }],
      },
      zIndex: {
        'base': 'var(--z-base)',
        'game': 'var(--z-game)',
        'hud': 'var(--z-hud)',
        'carousel-nav': 'var(--z-carousel-nav)',
        'dropdown': 'var(--z-dropdown)',
        'overlay': 'var(--z-overlay)',
        'crisis': 'var(--z-crisis)',
        'panel': 'var(--z-panel)',
        'deduction': 'var(--z-deduction)',
        'menu': 'var(--z-menu)',
        'briefing': 'var(--z-briefing)',
        'tab-bar': 'var(--z-tab-bar)',
        'modal-backdrop': 'var(--z-modal-backdrop)',
        'modal': 'var(--z-modal)',
        'sheet-backdrop': 'var(--z-sheet-backdrop)',
        'sheet': 'var(--z-sheet)',
        'confetti': 'var(--z-confetti)',
        'guess-dropdown': 'var(--z-guess-dropdown)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}