SET LOCAL search_path = public;

CREATE TABLE IF NOT EXISTS trait_tags (
  tag         text PRIMARY KEY CHECK (tag ~ '^[a-z_]+:[A-Za-z0-9_]+$'),
  category    text NOT NULL CHECK (category IN ('habitat','morphology','diet','behavior','reproduction','taxonomy','key_fact','geography','conservation')),
  is_filtering boolean NOT NULL DEFAULT true,
  description text
);

-- Owner-approved deletion of exactly the 22 archived unplayable profiles.
DELETE FROM species_deduction_profiles p
WHERE p.species_id IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22)
  AND NOT EXISTS (SELECT 1 FROM case_pool_members m WHERE m.species_id = p.species_id)
  AND NOT EXISTS (SELECT 1 FROM evidence_family_cards c WHERE c.species_id = p.species_id);
SELECT count(*) AS remaining_profiles FROM species_deduction_profiles;

-- Generated by scripts/generate-trait-tags.ts; includes concrete dynamic tags from dossiers.
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('activity_pattern:cathemeral', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('activity_pattern:crepuscular', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('activity_pattern:diurnal', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('activity_pattern:nocturnal', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('bioregion:comoros', 'geography', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('bioregion:namaqualand', 'geography', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('bioregion:sahara', 'geography', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('body_plan:armored', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('body_plan:compact', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('body_plan:elongated', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('body_plan:graceful', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('body_plan:robust', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('care_pattern:altricial', 'reproduction', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('care_pattern:den', 'reproduction', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('care_pattern:nest', 'reproduction', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('care_pattern:pouch', 'reproduction', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('care_pattern:precocial', 'reproduction', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('climate_zone:arctic', 'geography', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('climate_zone:arid', 'geography', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('climate_zone:montane', 'geography', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('climate_zone:temperate', 'geography', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('climate_zone:tropical', 'geography', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_behavior:not_canopy_colony', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_behavior:not_defensive_curler', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_behavior:not_desert_herd', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_behavior:not_matriarchal_herd', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_behavior:not_sand_swimmer', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_behavior:not_solitary_ambusher', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_diet:not_ant_specialist', 'diet', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_diet:not_bulk_browser', 'diet', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_diet:not_desert_browser', 'diet', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_diet:not_fruit_flower_forager', 'diet', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_diet:not_large_prey_hunter', 'diet', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_diet:not_soil_insect_hunter', 'diet', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_form:not_horned_antelope', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_form:not_sand_digger', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_form:not_scaled_digger', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_form:not_striped_cat', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_form:not_trunked_giant', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_form:not_winged_mammal', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_lineage:not_big_cat', 'taxonomy', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_lineage:not_bovid', 'taxonomy', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_lineage:not_elephant', 'taxonomy', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_lineage:not_fruit_bat', 'taxonomy', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_lineage:not_golden_mole', 'taxonomy', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_lineage:not_pangolin', 'taxonomy', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_range:not_asian_big_cat_range', 'geography', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_range:not_comoros_islands', 'geography', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_range:not_namaqualand_dunes', 'geography', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_range:not_sahara_sahel', 'geography', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_range:not_south_asian_mainland', 'geography', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('comparison_range:not_southeast_asian_forest', 'geography', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('continent:africa', 'geography', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('continent:asia', 'geography', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('diet_type:carnivore', 'diet', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('diet_type:folivore', 'diet', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('diet_type:frugivore', 'diet', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('diet_type:herbivore', 'diet', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('diet_type:insectivore', 'diet', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('diet_type:myrmecophage', 'diet', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('diet_type:nectarivore', 'diet', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('diet_type:omnivore', 'diet', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('diet_type:piscivore', 'diet', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('distinctive_features:antlers', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('distinctive_features:claws_climbing', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('distinctive_features:claws_digging', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('distinctive_features:horns', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('distinctive_features:mask_face', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('distinctive_features:pouch', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('distinctive_features:prehensile_tail', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('distinctive_features:quills', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('distinctive_features:scales', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('distinctive_features:spots', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('distinctive_features:stripes', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('distinctive_features:tuft_ears', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('distinctive_features:tusks', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('distinctive_features:webbed_feet', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('distinctive_features:wings', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('family:bovidae', 'taxonomy', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('family:chrysochloridae', 'taxonomy', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('family:elephantidae', 'taxonomy', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('family:felidae', 'taxonomy', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('family:manidae', 'taxonomy', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('family:pteropodidae', 'taxonomy', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('food_source:animals', 'diet', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('food_source:plants', 'diet', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('foraging_style:ambush', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('foraging_style:browse', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('foraging_style:dig', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('foraging_style:fish', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('foraging_style:forage', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('foraging_style:glean', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('foraging_style:graze', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('foraging_style:pursuit', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('foraging_style:scavenge', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('gameplay_size:large', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('gameplay_size:small_medium', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('genus:addax', 'taxonomy', false) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('genus:cryptochloris', 'taxonomy', false) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('genus:elephas', 'taxonomy', false) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('genus:manis', 'taxonomy', false) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('genus:panthera', 'taxonomy', false) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('genus:pteropus', 'taxonomy', false) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('habitat_tag:alpine', 'habitat', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('habitat_tag:cave', 'habitat', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('habitat_tag:coastal', 'habitat', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('habitat_tag:desert', 'habitat', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('habitat_tag:dry_forest', 'habitat', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('habitat_tag:grassland', 'habitat', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('habitat_tag:lake', 'habitat', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('habitat_tag:mangrove', 'habitat', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('habitat_tag:montane_forest', 'habitat', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('habitat_tag:rainforest', 'habitat', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('habitat_tag:river', 'habitat', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('habitat_tag:savanna', 'habitat', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('habitat_tag:tundra', 'habitat', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('habitat_tag:urban_fringe', 'habitat', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('habitat_tag:wetland', 'habitat', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('iucn:CR', 'conservation', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('iucn:DD', 'conservation', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('iucn:EN', 'conservation', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('iucn:EW', 'conservation', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('iucn:EX', 'conservation', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('iucn:LC', 'conservation', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('iucn:NE', 'conservation', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('iucn:NT', 'conservation', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('iucn:VU', 'conservation', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('lifespan_bucket:15_25y', 'reproduction', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('lifespan_bucket:25_50y', 'reproduction', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('lifespan_bucket:5_15y', 'reproduction', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('lifespan_bucket:over_50y', 'reproduction', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('lifespan_bucket:under_5y', 'reproduction', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('locomotion:arboreal', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('locomotion:cursorial', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('locomotion:fossorial', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('locomotion:saltatorial', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('locomotion:scansorial', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('locomotion:semi_aquatic', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('parity:iteroparous', 'reproduction', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('parity:semelparous', 'reproduction', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('research_signal:arboreal_foraging', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('research_signal:arid_ground', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('research_signal:contact_calls', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('research_signal:digging_trace', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('research_signal:endangered_megafauna_cohort', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('research_signal:forest_edge_feeding', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('research_signal:fragmented_forest', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('research_signal:ground_contact_travel', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('research_signal:herd_group', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('research_signal:keratin_defense', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('research_signal:large_ground_impression', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('research_signal:larger_than_mouse', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('research_signal:non_saharan_range', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('research_signal:non_scaled_body_cover', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('research_signal:nonvisual_foraging', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('research_signal:not_large_prey_specialist', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('research_signal:solitary_quiet', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('research_signal:substrate_vibration', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('research_signal:subtonne_body_mass', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('research_signal:tree_feeding_debris', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('research_signal:vertebrate_predation', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('signature:nearly_twenty_two_month_gestation', 'reproduction', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('signature:one_point_four_metre_wingspan', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('signature:plant_moisture_replaces_drinking', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('signature:rediscovered_by_soil_edna', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('signature:swims_eight_kilometers', 'key_fact', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('signature:young_rides_at_mothers_tail_base', 'reproduction', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('size_bucket:dog', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('size_bucket:elephant', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('size_bucket:horse', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('size_bucket:human', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('size_bucket:mouse', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('size_bucket:rabbit', 'morphology', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('social_pattern:group', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('social_pattern:solitary', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('sociality:colony', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('sociality:herd', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('sociality:pair', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('sociality:small_group', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('sociality:solitary', 'behavior', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('superorder:afrotheria', 'taxonomy', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('superorder:laurasiatheria', 'taxonomy', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('threat_tag:agriculture', 'conservation', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('threat_tag:climate_change', 'conservation', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('threat_tag:deforestation', 'conservation', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('threat_tag:disease', 'conservation', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('threat_tag:invasive', 'conservation', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('threat_tag:mining', 'conservation', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('threat_tag:pet_trade', 'conservation', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('threat_tag:poaching', 'conservation', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('threat_tag:pollution', 'conservation', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('threat_tag:roadkill', 'conservation', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('threat_tag:trophy_hunt', 'conservation', true) ON CONFLICT (tag) DO NOTHING;
INSERT INTO trait_tags (tag, category, is_filtering) VALUES ('threat_tag:urban_development', 'conservation', true) ON CONFLICT (tag) DO NOTHING;

CREATE OR REPLACE VIEW deduction_profile_unknown_tags AS
SELECT p.species_id, t.tag
FROM species_deduction_profiles p
CROSS JOIN LATERAL unnest(
  p.habitat_tags || p.morphology_tags || p.diet_tags || p.behavior_tags || p.reproduction_tags
  || p.taxonomy_tags || p.geography_tags || p.conservation_tags || p.key_fact_tags
) AS t(tag)
LEFT JOIN trait_tags k ON k.tag = t.tag
WHERE k.tag IS NULL;

SELECT count(*) AS vocabulary_size FROM trait_tags;
SELECT count(*) AS unknown_tags FROM deduction_profile_unknown_tags;
