-- Clue Match: 26 mammals join the pool (Clue Match had 22 frogs and turtles
-- plus the tiger and addax). Content drafted for grades 6-12 from well-established
-- facts; review it like any other content (docs/CLUE_MATCH.md).
--
--   1. Common names for species stored with only a scientific name.
--   2. Clues: family tree, body, behavior, diet, habitat, a range note, life
--      cycle, status and three key facts per species. Tagged clues narrow the
--      candidates; untagged ones are notes.
--   3. Facts: life cycle and threats, shown once a color's clues run out.
--
-- Then rerun 039 (realm Range clues for the new species) and refresh the
-- clue_match_ranges view (040). Idempotent: existing rows are left alone.
BEGIN;
SET LOCAL search_path = public;

UPDATE species s
SET common_name = v.common_name, updated_at = now()
FROM (VALUES
  ('Daubentonia madagascariensis', 'Aye-aye'),
  ('Mustela nigripes', 'Black-footed Ferret'),
  ('Zaglossus bruijnii', 'Western Long-beaked Echidna'),
  ('Okapia johnstoni', 'Okapi'),
  ('Bradypus pygmaeus', 'Pygmy Three-toed Sloth'),
  ('Lasiorhinus krefftii', 'Northern Hairy-nosed Wombat'),
  ('Canis simensis', 'Ethiopian Wolf'),
  ('Rhinopithecus roxellana', 'Golden Snub-nosed Monkey'),
  ('Ailurus fulgens', 'Red Panda'),
  ('Priodontes maximus', 'Giant Armadillo'),
  ('Macrotis lagotis', 'Greater Bilby'),
  ('Pseudoryx nghetinhensis', 'Saola'),
  ('Equus grevyi', 'Grévy''s Zebra'),
  ('Pongo abelii', 'Sumatran Orangutan'),
  ('Loxodonta cyclotis', 'African Forest Elephant'),
  ('Marmota vancouverensis', 'Vancouver Island Marmot'),
  ('Dendrolagus goodfellowi', 'Goodfellow''s Tree-kangaroo'),
  ('Rhinoceros sondaicus', 'Javan Rhinoceros'),
  ('Rhynchocyon chrysopygus', 'Golden-rumped Sengi'),
  ('Ochotona iliensis', 'Ili Pika'),
  ('Sarcophilus harrisii', 'Tasmanian Devil'),
  ('Solenodon paradoxus', 'Hispaniolan Solenodon')
) AS v(scientific_name, common_name)
WHERE s.scientific_name = v.scientific_name AND s.common_name = s.scientific_name;

INSERT INTO species_deduction_clues (species_id, category, reveal_order, label, compare_tags, is_filtering)
SELECT s.id, v.category, v.reveal_order, v.label, v.tags, v.is_filtering
FROM (VALUES
  ('Daubentonia madagascariensis', 'taxonomy', 1, 'Class: Mammalia, Order: Primates', ARRAY['mammalia', 'primates'], true),
  ('Daubentonia madagascariensis', 'taxonomy', 2, 'Family: Daubentoniidae, Genus: Daubentonia', ARRAY['daubentoniidae', 'daubentonia'], true),
  ('Daubentonia madagascariensis', 'morphology', 1, 'Big bat-like ears, huge eyes, front teeth that never stop growing, and one very thin, long middle finger.', ARRAY['large_ears', 'specialized_digit'], true),
  ('Daubentonia madagascariensis', 'morphology', 2, 'Primary color: Dark brown to black. Pattern: Shaggy coat with pale-tipped hairs and a big bushy tail.', ARRAY['dark_coloration', 'brown_coloration', 'bushy_tail'], true),
  ('Daubentonia madagascariensis', 'behavior', 1, 'Taps on tree bark with its long middle finger and listens for the hollow tunnels of beetle grubs.', ARRAY['tap_forager'], true),
  ('Daubentonia madagascariensis', 'behavior', 2, 'Active at night; spends the day curled up in a ball-shaped nest of leaves high in the trees.', ARRAY['nocturnal', 'nest_builder', 'solitary'], true),
  ('Daubentonia madagascariensis', 'diet', 1, 'Diet type: Omnivore. Eats: beetle grubs, seeds, nuts, fruit, nectar and fungi.', ARRAY['omnivore', 'insect_eater', 'frugivore', 'granivore'], true),
  ('Daubentonia madagascariensis', 'habitat', 1, 'Lives high in the trees of tropical rainforests and dry forests.', ARRAY['forest', 'tropical', 'arboreal', 'terrestrial'], true),
  ('Daubentonia madagascariensis', 'habitat', 2, 'Also visits mangroves and coconut and lychee plantations when searching for food.', ARRAY['forest', 'coastal'], true),
  ('Daubentonia madagascariensis', 'geography', 1, 'Found across much of Madagascar, from the eastern rainforests to the dry forests of the west and north.', ARRAY[]::text[], false),
  ('Daubentonia madagascariensis', 'reproduction', 1, 'Reproduction: Gives birth to live young. Young: 1 every 2 to 3 years. Lifespan: about 20 years', ARRAY['live_birth'], true),
  ('Daubentonia madagascariensis', 'conservation', 1, 'Status: Endangered. Forest clearing, and old beliefs that it brings bad luck, put it at risk.', ARRAY[]::text[], false),
  ('Daubentonia madagascariensis', 'key_fact', 1, 'It does the job of a woodpecker in Madagascar, where there are no woodpeckers.', ARRAY[]::text[], false),
  ('Daubentonia madagascariensis', 'key_fact', 2, 'Its skinny middle finger sits on a ball-and-socket joint, so it can turn in almost any direction.', ARRAY[]::text[], false),
  ('Daubentonia madagascariensis', 'key_fact', 3, 'Its front teeth keep growing all its life, so early scientists thought it was a kind of squirrel.', ARRAY[]::text[], false),
  ('Manis javanica', 'taxonomy', 1, 'Class: Mammalia, Order: Pholidota', ARRAY['mammalia', 'pholidota'], true),
  ('Manis javanica', 'taxonomy', 2, 'Family: Manidae, Genus: Manis', ARRAY['manidae', 'manis'], true),
  ('Manis javanica', 'morphology', 1, 'Covered in overlapping scales like a walking pinecone, with a long sticky tongue and no teeth.', ARRAY['scaled', 'toothless'], true),
  ('Manis javanica', 'morphology', 2, 'Primary color: Brown to yellowish brown. Pattern: Rows of overlapping scales from head to tail.', ARRAY['brown_coloration', 'yellow_coloration', 'scaled'], true),
  ('Manis javanica', 'behavior', 1, 'Rolls into a tight, armored ball when it feels threatened.', ARRAY['rolls_into_ball'], true),
  ('Manis javanica', 'behavior', 2, 'Active at night; climbs trees using its grasping tail and sleeps in tree hollows or burrows.', ARRAY['nocturnal', 'climber', 'solitary'], true),
  ('Manis javanica', 'diet', 1, 'Diet type: Insectivore. Eats: ants and termites, found with its strong sense of smell.', ARRAY['insect_eater', 'carnivore'], true),
  ('Manis javanica', 'habitat', 1, 'Lives in tropical forests, from old rainforest to plantations and gardens.', ARRAY['forest', 'tropical', 'arboreal', 'terrestrial'], true),
  ('Manis javanica', 'habitat', 2, 'Rests in tree hollows or in burrows it digs with its strong front claws.', ARRAY['forest', 'burrower_habitat'], true),
  ('Manis javanica', 'geography', 1, 'Found across Southeast Asia, from Myanmar and Thailand to Malaysia, Sumatra, Java and Borneo.', ARRAY[]::text[], false),
  ('Manis javanica', 'reproduction', 1, 'Reproduction: Gives birth to live young. Young: 1 at a time; the baby rides on its mother''s tail. Lifespan: about 20 years', ARRAY['live_birth'], true),
  ('Manis javanica', 'conservation', 1, 'Status: Critically Endangered. It is one of the most illegally traded mammals in the world, taken for its scales and meat.', ARRAY[]::text[], false),
  ('Manis javanica', 'key_fact', 1, 'Its scales are made of keratin, the same material as your fingernails.', ARRAY[]::text[], false),
  ('Manis javanica', 'key_fact', 2, 'Its long, sticky tongue starts deep inside its body, near its hips.', ARRAY[]::text[], false),
  ('Manis javanica', 'key_fact', 3, 'It has no teeth; small stones it swallows help grind up food in its stomach.', ARRAY[]::text[], false),
  ('Mustela nigripes', 'taxonomy', 1, 'Class: Mammalia, Order: Carnivora', ARRAY['mammalia', 'carnivora'], true),
  ('Mustela nigripes', 'taxonomy', 2, 'Family: Mustelidae, Genus: Mustela', ARRAY['mustelidae', 'mustela'], true),
  ('Mustela nigripes', 'morphology', 1, 'Long, slim body with short legs, a black face mask, black feet and a black tail tip.', ARRAY['slender', 'masked_face'], true),
  ('Mustela nigripes', 'morphology', 2, 'Primary color: Sandy tan. Pattern: Black mask across the eyes, black legs and feet.', ARRAY['yellow_coloration', 'brown_coloration', 'dark_coloration', 'masked_face'], true),
  ('Mustela nigripes', 'behavior', 1, 'Hunts mostly at night and moves through prairie dog tunnels.', ARRAY['nocturnal', 'burrower', 'solitary'], true),
  ('Mustela nigripes', 'behavior', 2, 'Spends most of its life underground, coming up mainly at night.', ARRAY['burrower'], true),
  ('Mustela nigripes', 'diet', 1, 'Diet type: Carnivore. Preys on: prairie dogs, which make up about 90% of its diet.', ARRAY['carnivore'], true),
  ('Mustela nigripes', 'habitat', 1, 'Lives on short-grass and mixed-grass prairies.', ARRAY['grassland', 'temperate', 'terrestrial'], true),
  ('Mustela nigripes', 'habitat', 2, 'Needs large prairie dog towns, where it finds both food and shelter.', ARRAY['grassland', 'burrower_habitat'], true),
  ('Mustela nigripes', 'geography', 1, 'Once found across the Great Plains; now lives only where it has been released in the western United States, Canada and Mexico.', ARRAY[]::text[], false),
  ('Mustela nigripes', 'reproduction', 1, 'Reproduction: Gives birth to live young. Litter: 3 to 4 kits. Lifespan: 3 to 4 years in the wild', ARRAY['live_birth', 'short_lived'], true),
  ('Mustela nigripes', 'conservation', 1, 'Status: Endangered. It was once thought extinct; every black-footed ferret alive today comes from 18 animals saved in the 1980s.', ARRAY[]::text[], false),
  ('Mustela nigripes', 'key_fact', 1, 'Scientists thought it was extinct until a ranch dog found one in Wyoming in 1981.', ARRAY[]::text[], false),
  ('Mustela nigripes', 'key_fact', 2, 'A single black-footed ferret may eat more than 100 prairie dogs in a year.', ARRAY[]::text[], false),
  ('Mustela nigripes', 'key_fact', 3, 'In 2020 scientists cloned a black-footed ferret, named Elizabeth Ann, to add new genes to the population.', ARRAY[]::text[], false),
  ('Zaglossus bruijnii', 'taxonomy', 1, 'Class: Mammalia, Order: Monotremata', ARRAY['mammalia', 'monotremata'], true),
  ('Zaglossus bruijnii', 'taxonomy', 2, 'Family: Tachyglossidae, Genus: Zaglossus', ARRAY['tachyglossidae', 'zaglossus'], true),
  ('Zaglossus bruijnii', 'morphology', 1, 'Long, down-curved snout, short spines hidden in thick fur, and strong clawed feet.', ARRAY['specialized_snout', 'spined'], true),
  ('Zaglossus bruijnii', 'morphology', 2, 'Primary color: Dark brown to black. Pattern: Pale spines poking through thick dark fur.', ARRAY['dark_coloration', 'brown_coloration', 'spined'], true),
  ('Zaglossus bruijnii', 'behavior', 1, 'Active mostly at night, snuffling through leaf litter with its long snout.', ARRAY['nocturnal', 'solitary'], true),
  ('Zaglossus bruijnii', 'behavior', 2, 'When threatened, it digs itself into the soil to protect its soft belly.', ARRAY['burrower'], true),
  ('Zaglossus bruijnii', 'diet', 1, 'Diet type: Insectivore. Eats: mostly earthworms, plus beetle larvae and other insects.', ARRAY['vermivore', 'insect_eater', 'carnivore'], true),
  ('Zaglossus bruijnii', 'habitat', 1, 'Lives in hill and mountain forests and alpine meadows.', ARRAY['forest', 'montane', 'tropical', 'grassland', 'terrestrial'], true),
  ('Zaglossus bruijnii', 'habitat', 2, 'Usually found high up, above 1,000 m, in cool, wet mountain forest.', ARRAY['montane', 'forest'], true),
  ('Zaglossus bruijnii', 'geography', 1, 'Found only in the Bird''s Head Peninsula of western New Guinea and a nearby island, in Indonesia.', ARRAY[]::text[], false),
  ('Zaglossus bruijnii', 'reproduction', 1, 'Reproduction: Lays a single leathery egg, which hatches in the mother''s pouch. Lifespan: 30 years or more', ARRAY['egg_laying'], true),
  ('Zaglossus bruijnii', 'conservation', 1, 'Status: Critically Endangered. Hunting and forest clearing have made it very rare.', ARRAY[]::text[], false),
  ('Zaglossus bruijnii', 'key_fact', 1, 'It is a mammal that lays eggs, one of only five such species alive today.', ARRAY[]::text[], false),
  ('Zaglossus bruijnii', 'key_fact', 2, 'It has no teeth; tiny spikes on its tongue help it grab worms.', ARRAY[]::text[], false),
  ('Zaglossus bruijnii', 'key_fact', 3, 'A baby echidna is called a puggle.', ARRAY[]::text[], false),
  ('Elephas maximus', 'taxonomy', 1, 'Class: Mammalia, Order: Proboscidea', ARRAY['mammalia', 'proboscidea'], true),
  ('Elephas maximus', 'taxonomy', 2, 'Family: Elephantidae, Genus: Elephas', ARRAY['elephantidae', 'elephas'], true),
  ('Elephas maximus', 'morphology', 1, 'Huge body, a long trunk with one finger-like tip, and smaller ears than African elephants.', ARRAY['large_bodied', 'trunk'], true),
  ('Elephas maximus', 'morphology', 2, 'Primary color: Grey, often with pink patches. Pattern: Only some males grow tusks.', ARRAY['grey_coloration', 'tusks'], true),
  ('Elephas maximus', 'behavior', 1, 'Females and young live in family herds led by an older female.', ARRAY['herd', 'social'], true),
  ('Elephas maximus', 'behavior', 2, 'A strong swimmer that can use its trunk like a snorkel.', ARRAY['swimmer'], true),
  ('Elephas maximus', 'diet', 1, 'Diet type: Herbivore. Eats: grasses, bark, roots, leaves and fruit, for up to 19 hours a day.', ARRAY['herbivore', 'grazer', 'folivore', 'frugivore'], true),
  ('Elephas maximus', 'habitat', 1, 'Lives in tropical forests with grassy openings, from lowlands to hills.', ARRAY['forest', 'tropical', 'grassland', 'terrestrial'], true),
  ('Elephas maximus', 'habitat', 2, 'Needs plenty of water and travels long distances between feeding areas.', ARRAY['freshwater'], true),
  ('Elephas maximus', 'geography', 1, 'Found in 13 countries of South and Southeast Asia, from India and Sri Lanka to Borneo.', ARRAY[]::text[], false),
  ('Elephas maximus', 'reproduction', 1, 'Reproduction: Gives birth to live young after nearly 2 years of pregnancy. Young: 1 calf. Lifespan: about 60 years', ARRAY['live_birth', 'long_lived'], true),
  ('Elephas maximus', 'conservation', 1, 'Status: Endangered. Loss of forests, conflict with farmers and poaching for ivory threaten it.', ARRAY[]::text[], false),
  ('Elephas maximus', 'key_fact', 1, 'Its trunk has tens of thousands of muscles and can pick up a single blade of grass.', ARRAY[]::text[], false),
  ('Elephas maximus', 'key_fact', 2, 'Asian elephants have one finger-like tip on the trunk; African elephants have two.', ARRAY[]::text[], false),
  ('Elephas maximus', 'key_fact', 3, 'Elephants can hear low rumbles from other elephants several kilometres away.', ARRAY[]::text[], false),
  ('Okapia johnstoni', 'taxonomy', 1, 'Class: Mammalia, Order: Artiodactyla', ARRAY['mammalia', 'artiodactyla'], true),
  ('Okapia johnstoni', 'taxonomy', 2, 'Family: Giraffidae, Genus: Okapia', ARRAY['giraffidae', 'okapia'], true),
  ('Okapia johnstoni', 'morphology', 1, 'Looks like a mix of a horse and a zebra, with a long neck, large ears and a very long tongue.', ARRAY['large_bodied', 'large_ears'], true),
  ('Okapia johnstoni', 'morphology', 2, 'Primary color: Dark reddish-brown. Pattern: White and black stripes on the legs and rump.', ARRAY['brown_coloration', 'red_coloration', 'dark_coloration', 'striped'], true),
  ('Okapia johnstoni', 'behavior', 1, 'Shy and solitary; walks the same trails through the forest again and again.', ARRAY['solitary'], true),
  ('Okapia johnstoni', 'behavior', 2, 'Active mostly by day and very quiet, so it is hard to spot.', ARRAY['diurnal'], true),
  ('Okapia johnstoni', 'diet', 1, 'Diet type: Herbivore. Eats: leaves, buds, fruit, ferns and fungi.', ARRAY['herbivore', 'folivore', 'frugivore'], true),
  ('Okapia johnstoni', 'habitat', 1, 'Lives in dense tropical rainforest.', ARRAY['forest', 'tropical', 'terrestrial'], true),
  ('Okapia johnstoni', 'habitat', 2, 'Stays deep in the forest, far from open grassland.', ARRAY['forest'], true),
  ('Okapia johnstoni', 'geography', 1, 'Found only in the rainforests of the Democratic Republic of the Congo, in central Africa.', ARRAY[]::text[], false),
  ('Okapia johnstoni', 'reproduction', 1, 'Reproduction: Gives birth to live young after about 15 months. Young: 1 calf. Lifespan: 20 to 30 years', ARRAY['live_birth'], true),
  ('Okapia johnstoni', 'conservation', 1, 'Status: Endangered. Forest loss, hunting and unrest in its home region have cut its numbers.', ARRAY[]::text[], false),
  ('Okapia johnstoni', 'key_fact', 1, 'Its closest living relative is the giraffe, not the zebra.', ARRAY[]::text[], false),
  ('Okapia johnstoni', 'key_fact', 2, 'Its tongue is long enough to lick its own eyes and ears clean.', ARRAY[]::text[], false),
  ('Okapia johnstoni', 'key_fact', 3, 'Scientists outside Africa only learned about the okapi in 1901.', ARRAY[]::text[], false),
  ('Bradypus pygmaeus', 'taxonomy', 1, 'Class: Mammalia, Order: Pilosa', ARRAY['mammalia', 'pilosa'], true),
  ('Bradypus pygmaeus', 'taxonomy', 2, 'Family: Bradypodidae, Genus: Bradypus', ARRAY['bradypodidae', 'bradypus'], true),
  ('Bradypus pygmaeus', 'morphology', 1, 'A small, slow sloth with three long, curved claws on each front foot.', ARRAY['long_claws'], true),
  ('Bradypus pygmaeus', 'morphology', 2, 'Primary color: Greyish brown, often tinted green by algae. Pattern: Dark stripe across the eyes and a pale face.', ARRAY['grey_coloration', 'brown_coloration', 'green_coloration', 'masked_face'], true),
  ('Bradypus pygmaeus', 'behavior', 1, 'Moves very slowly and hangs upside down in trees for most of its life.', ARRAY['climber', 'slow_mover'], true),
  ('Bradypus pygmaeus', 'behavior', 2, 'A surprisingly good swimmer.', ARRAY['swimmer'], true),
  ('Bradypus pygmaeus', 'diet', 1, 'Diet type: Herbivore. Eats: mostly the leaves of red mangrove trees.', ARRAY['herbivore', 'folivore'], true),
  ('Bradypus pygmaeus', 'habitat', 1, 'Lives in red mangrove forests along the coast.', ARRAY['forest', 'coastal', 'tropical', 'arboreal', 'wetland'], true),
  ('Bradypus pygmaeus', 'habitat', 2, 'Found on a single small island of only about 4 square kilometres.', ARRAY['coastal', 'island'], true),
  ('Bradypus pygmaeus', 'geography', 1, 'Found only on Isla Escudo de Veraguas, an island off the Caribbean coast of Panama.', ARRAY[]::text[], false),
  ('Bradypus pygmaeus', 'reproduction', 1, 'Reproduction: Gives birth to live young. Young: 1 at a time.', ARRAY['live_birth'], true),
  ('Bradypus pygmaeus', 'conservation', 1, 'Status: Critically Endangered. Only a small number live on its one island, where mangroves are being cut.', ARRAY[]::text[], false),
  ('Bradypus pygmaeus', 'key_fact', 1, 'It is the smallest of the three-toed sloths.', ARRAY[]::text[], false),
  ('Bradypus pygmaeus', 'key_fact', 2, 'It became its own species after its island was cut off from the mainland about 9,000 years ago.', ARRAY[]::text[], false),
  ('Bradypus pygmaeus', 'key_fact', 3, 'Algae growing in its fur give it a greenish color that helps it hide in the trees.', ARRAY[]::text[], false),
  ('Lasiorhinus krefftii', 'taxonomy', 1, 'Class: Mammalia, Order: Diprotodontia', ARRAY['mammalia', 'diprotodontia'], true),
  ('Lasiorhinus krefftii', 'taxonomy', 2, 'Family: Vombatidae, Genus: Lasiorhinus', ARRAY['vombatidae', 'lasiorhinus'], true),
  ('Lasiorhinus krefftii', 'morphology', 1, 'Stocky, barrel-shaped body with short legs, a broad hairy nose and strong digging claws.', ARRAY['rounded_body', 'robust'], true),
  ('Lasiorhinus krefftii', 'morphology', 2, 'Primary color: Soft grey-brown. Pattern: Fine fur, pointed ears and a furry muzzle.', ARRAY['grey_coloration', 'brown_coloration'], true),
  ('Lasiorhinus krefftii', 'behavior', 1, 'Digs long burrows and stays underground during the heat of the day, coming out at night.', ARRAY['burrower', 'nocturnal'], true),
  ('Lasiorhinus krefftii', 'behavior', 2, 'Mostly solitary, though neighbors may share groups of burrows.', ARRAY['solitary'], true),
  ('Lasiorhinus krefftii', 'diet', 1, 'Diet type: Herbivore. Eats: native grasses, roots and sedges.', ARRAY['herbivore', 'grazer'], true),
  ('Lasiorhinus krefftii', 'habitat', 1, 'Lives in semi-dry open woodland with deep, sandy soil.', ARRAY['forest', 'grassland', 'arid', 'terrestrial'], true),
  ('Lasiorhinus krefftii', 'habitat', 2, 'Needs soft, sandy soil to dig its burrows.', ARRAY['burrower_habitat'], true),
  ('Lasiorhinus krefftii', 'geography', 1, 'Found only in two protected places in Queensland, Australia: Epping Forest National Park and the Richard Underwood Nature Refuge.', ARRAY[]::text[], false),
  ('Lasiorhinus krefftii', 'reproduction', 1, 'Reproduction: Gives birth to a tiny baby that grows in a pouch. Young: 1 joey. Lifespan: 25 years or more', ARRAY['live_birth', 'pouch'], true),
  ('Lasiorhinus krefftii', 'conservation', 1, 'Status: Critically Endangered. By the 1980s only about 35 were left; careful protection has helped numbers grow.', ARRAY[]::text[], false),
  ('Lasiorhinus krefftii', 'key_fact', 1, 'Its pouch faces backward, so dirt does not get in when it digs.', ARRAY[]::text[], false),
  ('Lasiorhinus krefftii', 'key_fact', 2, 'Wombats make cube-shaped droppings.', ARRAY[]::text[], false),
  ('Lasiorhinus krefftii', 'key_fact', 3, 'It is one of the rarest large mammals on Earth.', ARRAY[]::text[], false),
  ('Cryptochloris wintoni', 'taxonomy', 1, 'Class: Mammalia, Order: Afrosoricida', ARRAY['mammalia', 'afrosoricida'], true),
  ('Cryptochloris wintoni', 'taxonomy', 2, 'Family: Chrysochloridae, Genus: Cryptochloris', ARRAY['chrysochloridae', 'cryptochloris'], true),
  ('Cryptochloris wintoni', 'morphology', 1, 'Tiny body with silky fur, eyes hidden under skin, a leathery nose pad and big digging claws.', ARRAY['tiny', 'long_claws'], true),
  ('Cryptochloris wintoni', 'morphology', 2, 'Primary color: Pale yellowish grey. Pattern: Fur with a shiny, golden sheen.', ARRAY['yellow_coloration', 'grey_coloration'], true),
  ('Cryptochloris wintoni', 'behavior', 1, '''Swims'' through loose sand just under the surface instead of digging lasting tunnels.', ARRAY['burrower', 'sand_swimmer'], true),
  ('Cryptochloris wintoni', 'behavior', 2, 'Senses tiny vibrations in the sand to find food.', ARRAY['vibration_sense'], true),
  ('Cryptochloris wintoni', 'diet', 1, 'Diet type: Insectivore. Eats: insects, worms and other small animals in the sand.', ARRAY['insect_eater', 'vermivore', 'carnivore'], true),
  ('Cryptochloris wintoni', 'habitat', 1, 'Lives in coastal sand dunes with low shrubs.', ARRAY['coastal', 'arid', 'scrubland', 'terrestrial'], true),
  ('Cryptochloris wintoni', 'habitat', 2, 'Needs loose, soft sand that it can move through.', ARRAY['burrower_habitat'], true),
  ('Cryptochloris wintoni', 'geography', 1, 'Known only from a small stretch of the Namaqualand coast in South Africa, near Port Nolloth.', ARRAY[]::text[], false),
  ('Cryptochloris wintoni', 'reproduction', 1, 'Reproduction: Gives birth to live young.', ARRAY['live_birth'], true),
  ('Cryptochloris wintoni', 'conservation', 1, 'Status: Critically Endangered. Diamond mining and building along the coast have destroyed much of its dune habitat.', ARRAY[]::text[], false),
  ('Cryptochloris wintoni', 'key_fact', 1, 'It was lost to science for 86 years until scientists found it again in 2023.', ARRAY[]::text[], false),
  ('Cryptochloris wintoni', 'key_fact', 2, 'It was found again using eDNA: tiny traces of DNA in the sand, gathered with help from a detection dog.', ARRAY[]::text[], false),
  ('Cryptochloris wintoni', 'key_fact', 3, 'Like other golden moles, its fur can shimmer with rainbow colors in the light.', ARRAY[]::text[], false),
  ('Canis simensis', 'taxonomy', 1, 'Class: Mammalia, Order: Carnivora', ARRAY['mammalia', 'carnivora'], true),
  ('Canis simensis', 'taxonomy', 2, 'Family: Canidae, Genus: Canis', ARRAY['canidae', 'canis'], true),
  ('Canis simensis', 'morphology', 1, 'Long legs, a long narrow snout and a bushy tail, a bit like a slim fox.', ARRAY['slender', 'bushy_tail'], true),
  ('Canis simensis', 'morphology', 2, 'Primary color: Bright reddish orange. Pattern: White throat, chest and belly, with a dark tail tip.', ARRAY['red_coloration', 'white_markings'], true),
  ('Canis simensis', 'behavior', 1, 'Lives in packs that share a territory, but hunts alone during the day.', ARRAY['social', 'diurnal'], true),
  ('Canis simensis', 'behavior', 2, 'Pack members greet each other with loud, excited calls.', ARRAY['vocal'], true),
  ('Canis simensis', 'diet', 1, 'Diet type: Carnivore. Preys on: mostly giant mole rats and other highland rodents.', ARRAY['carnivore'], true),
  ('Canis simensis', 'habitat', 1, 'Lives on cold mountain grasslands called Afroalpine meadows, above 3,000 m.', ARRAY['grassland', 'montane', 'terrestrial'], true),
  ('Canis simensis', 'habitat', 2, 'Prefers open moorland where rodents are plentiful.', ARRAY['grassland'], true),
  ('Canis simensis', 'geography', 1, 'Found only in a few mountain ranges in the highlands of Ethiopia, including the Bale Mountains.', ARRAY[]::text[], false),
  ('Canis simensis', 'reproduction', 1, 'Reproduction: Gives birth to live young in a den. Litter: 2 to 6 pups. Lifespan: about 8 to 10 years', ARRAY['live_birth', 'short_lived'], true),
  ('Canis simensis', 'conservation', 1, 'Status: Endangered. Fewer than 500 adults remain; diseases caught from pet dogs and loss of habitat threaten them.', ARRAY[]::text[], false),
  ('Canis simensis', 'key_fact', 1, 'It is Africa''s most threatened carnivore.', ARRAY[]::text[], false),
  ('Canis simensis', 'key_fact', 2, 'Other wolves in the pack help feed and guard the pups.', ARRAY[]::text[], false),
  ('Canis simensis', 'key_fact', 3, 'It is closely related to the gray wolf and the coyote.', ARRAY[]::text[], false),
  ('Rhinopithecus roxellana', 'taxonomy', 1, 'Class: Mammalia, Order: Primates', ARRAY['mammalia', 'primates'], true),
  ('Rhinopithecus roxellana', 'taxonomy', 2, 'Family: Cercopithecidae, Genus: Rhinopithecus', ARRAY['cercopithecidae', 'rhinopithecus'], true),
  ('Rhinopithecus roxellana', 'morphology', 1, 'Thick, long fur, a pale blue face and a tiny upturned nose.', ARRAY['snub_nose', 'long_fur'], true),
  ('Rhinopithecus roxellana', 'morphology', 2, 'Primary color: Bright golden orange. Pattern: Dark brown back and a blue face.', ARRAY['yellow_coloration', 'brown_coloration', 'blue_coloration'], true),
  ('Rhinopithecus roxellana', 'behavior', 1, 'Lives in large, social bands that can number hundreds of monkeys.', ARRAY['social'], true),
  ('Rhinopithecus roxellana', 'behavior', 2, 'Spends most of its time in the trees but also looks for food on the ground.', ARRAY['climber'], true),
  ('Rhinopithecus roxellana', 'diet', 1, 'Diet type: Herbivore. Eats: lichens in winter, plus leaves, buds, bark, seeds and fruit.', ARRAY['herbivore', 'folivore', 'frugivore', 'granivore'], true),
  ('Rhinopithecus roxellana', 'habitat', 1, 'Lives in cold mountain forests that are often covered in snow in winter.', ARRAY['forest', 'montane', 'temperate', 'arboreal', 'terrestrial'], true),
  ('Rhinopithecus roxellana', 'habitat', 2, 'Found at 1,500 to 3,400 m above sea level.', ARRAY['montane'], true),
  ('Rhinopithecus roxellana', 'geography', 1, 'Found only in mountain forests of central and southwestern China.', ARRAY[]::text[], false),
  ('Rhinopithecus roxellana', 'reproduction', 1, 'Reproduction: Gives birth to live young. Young: 1 baby about every 2 years. Lifespan: about 20 years', ARRAY['live_birth'], true),
  ('Rhinopithecus roxellana', 'conservation', 1, 'Status: Endangered. Logging and hunting reduced its numbers; nature reserves are helping.', ARRAY[]::text[], false),
  ('Rhinopithecus roxellana', 'key_fact', 1, 'It is one of the most cold-tolerant primates, living where winter temperatures fall far below freezing.', ARRAY[]::text[], false),
  ('Rhinopithecus roxellana', 'key_fact', 2, 'Its tiny nose is thought to help it cope with freezing winters.', ARRAY[]::text[], false),
  ('Rhinopithecus roxellana', 'key_fact', 3, 'Babies are cared for by several adults in the group, not just their mothers.', ARRAY[]::text[], false),
  ('Ailurus fulgens', 'taxonomy', 1, 'Class: Mammalia, Order: Carnivora', ARRAY['mammalia', 'carnivora'], true),
  ('Ailurus fulgens', 'taxonomy', 2, 'Family: Ailuridae, Genus: Ailurus', ARRAY['ailuridae', 'ailurus'], true),
  ('Ailurus fulgens', 'morphology', 1, 'Cat-sized, with a round face, pointed ears and a long, bushy, ringed tail.', ARRAY['bushy_tail', 'ringed_tail'], true),
  ('Ailurus fulgens', 'morphology', 2, 'Primary color: Rusty red. Pattern: White face markings, dark legs and a striped tail.', ARRAY['red_coloration', 'brown_coloration', 'dark_coloration', 'striped'], true),
  ('Ailurus fulgens', 'behavior', 1, 'Spends much of its time alone in the trees and sleeps curled up on branches.', ARRAY['climber', 'solitary'], true),
  ('Ailurus fulgens', 'behavior', 2, 'Most active at dawn and dusk.', ARRAY['crepuscular'], true),
  ('Ailurus fulgens', 'diet', 1, 'Diet type: Herbivore (mostly). Eats: bamboo leaves and shoots, plus fruit, acorns and the odd egg.', ARRAY['herbivore', 'folivore', 'frugivore'], true),
  ('Ailurus fulgens', 'habitat', 1, 'Lives in cool mountain forests with a thick bamboo understory.', ARRAY['forest', 'montane', 'temperate', 'arboreal', 'terrestrial'], true),
  ('Ailurus fulgens', 'habitat', 2, 'Found at 2,200 to 4,800 m above sea level.', ARRAY['montane'], true),
  ('Ailurus fulgens', 'geography', 1, 'Found in the eastern Himalayas and mountains of southwestern China, including Nepal, India, Bhutan and Myanmar.', ARRAY[]::text[], false),
  ('Ailurus fulgens', 'reproduction', 1, 'Reproduction: Gives birth to live young. Litter: 1 to 4 cubs. Lifespan: about 8 to 10 years in the wild', ARRAY['live_birth', 'short_lived'], true),
  ('Ailurus fulgens', 'conservation', 1, 'Status: Endangered. Forest loss and the illegal pet trade threaten it.', ARRAY[]::text[], false),
  ('Ailurus fulgens', 'key_fact', 1, 'It was called a panda before the giant panda was, and the two are not close relatives.', ARRAY[]::text[], false),
  ('Ailurus fulgens', 'key_fact', 2, 'A special wrist bone works like an extra thumb for gripping bamboo.', ARRAY[]::text[], false),
  ('Ailurus fulgens', 'key_fact', 3, 'It wraps its bushy tail around itself like a blanket when it is cold.', ARRAY[]::text[], false),
  ('Priodontes maximus', 'taxonomy', 1, 'Class: Mammalia, Order: Cingulata', ARRAY['mammalia', 'cingulata'], true),
  ('Priodontes maximus', 'taxonomy', 2, 'Family: Chlamyphoridae, Genus: Priodontes', ARRAY['chlamyphoridae', 'priodontes'], true),
  ('Priodontes maximus', 'morphology', 1, 'The largest armadillo, with a flexible armored shell and a huge claw on each front foot.', ARRAY['large_bodied', 'shelled', 'long_claws'], true),
  ('Priodontes maximus', 'morphology', 2, 'Primary color: Dark brown shell. Pattern: A pale band along the lower edge of the shell.', ARRAY['dark_coloration', 'brown_coloration'], true),
  ('Priodontes maximus', 'behavior', 1, 'Active at night; digs a new, large burrow almost every night.', ARRAY['burrower', 'nocturnal', 'solitary'], true),
  ('Priodontes maximus', 'behavior', 2, 'Its old burrows become shelters for many other animals.', ARRAY['ecosystem_engineer'], true),
  ('Priodontes maximus', 'diet', 1, 'Diet type: Insectivore. Eats: mostly termites and ants, plus worms and other small animals.', ARRAY['insect_eater', 'carnivore'], true),
  ('Priodontes maximus', 'habitat', 1, 'Lives in tropical forests and savannas.', ARRAY['forest', 'grassland', 'tropical', 'terrestrial'], true),
  ('Priodontes maximus', 'habitat', 2, 'Often found near termite mounds, where it digs for food.', ARRAY['grassland'], true),
  ('Priodontes maximus', 'geography', 1, 'Found across much of South America east of the Andes, from Venezuela to northern Argentina.', ARRAY[]::text[], false),
  ('Priodontes maximus', 'reproduction', 1, 'Reproduction: Gives birth to live young. Young: 1 pup, which stays in the burrow for weeks.', ARRAY['live_birth'], true),
  ('Priodontes maximus', 'conservation', 1, 'Status: Vulnerable. Hunting and forest clearing have made it rare.', ARRAY[]::text[], false),
  ('Priodontes maximus', 'key_fact', 1, 'Its middle front claw can be about 20 cm long, among the largest claws of any living animal for its size.', ARRAY[]::text[], false),
  ('Priodontes maximus', 'key_fact', 2, 'It can have up to 100 small teeth, more than almost any other land mammal.', ARRAY[]::text[], false),
  ('Priodontes maximus', 'key_fact', 3, 'It can weigh as much as a large dog, about 50 kg.', ARRAY[]::text[], false),
  ('Macrotis lagotis', 'taxonomy', 1, 'Class: Mammalia, Order: Peramelemorphia', ARRAY['mammalia', 'peramelemorphia'], true),
  ('Macrotis lagotis', 'taxonomy', 2, 'Family: Thylacomyidae, Genus: Macrotis', ARRAY['thylacomyidae', 'macrotis'], true),
  ('Macrotis lagotis', 'morphology', 1, 'Rabbit-sized, with very long ears, a long pointed snout and a long tail.', ARRAY['large_ears', 'specialized_snout'], true),
  ('Macrotis lagotis', 'morphology', 2, 'Primary color: Soft blue-grey. Pattern: Black and white tail with a white tip.', ARRAY['grey_coloration', 'blue_coloration', 'dark_coloration'], true),
  ('Macrotis lagotis', 'behavior', 1, 'Active at night; digs deep spiral burrows to escape the desert heat.', ARRAY['nocturnal', 'burrower', 'solitary'], true),
  ('Macrotis lagotis', 'behavior', 2, 'Uses its big ears to hear insects underground and to let off body heat.', ARRAY['burrower'], true),
  ('Macrotis lagotis', 'diet', 1, 'Diet type: Omnivore. Eats: insects, larvae, seeds, bulbs, fruit and fungi.', ARRAY['omnivore', 'insect_eater', 'granivore', 'frugivore', 'fungivore'], true),
  ('Macrotis lagotis', 'habitat', 1, 'Lives in deserts and dry grasslands.', ARRAY['arid', 'grassland', 'scrubland', 'terrestrial'], true),
  ('Macrotis lagotis', 'habitat', 2, 'Digs burrows up to 2 m deep in sandy or rocky soil.', ARRAY['burrower_habitat', 'rocky'], true),
  ('Macrotis lagotis', 'geography', 1, 'Found in scattered parts of central and western Australia.', ARRAY[]::text[], false),
  ('Macrotis lagotis', 'reproduction', 1, 'Reproduction: Gives birth to tiny babies that grow in a backward-facing pouch. Litter: 1 to 3. Lifespan: about 6 to 7 years', ARRAY['live_birth', 'pouch', 'short_lived'], true),
  ('Macrotis lagotis', 'conservation', 1, 'Status: Vulnerable. Foxes, feral cats and land changes have wiped it out from most of its old range.', ARRAY[]::text[], false),
  ('Macrotis lagotis', 'key_fact', 1, 'In Australia, many people celebrate with chocolate Easter Bilbies instead of Easter Bunnies.', ARRAY[]::text[], false),
  ('Macrotis lagotis', 'key_fact', 2, 'It does not need to drink; it gets water from its food.', ARRAY[]::text[], false),
  ('Macrotis lagotis', 'key_fact', 3, 'Its pregnancy lasts only about two weeks, one of the shortest of any mammal.', ARRAY[]::text[], false),
  ('Pseudoryx nghetinhensis', 'taxonomy', 1, 'Class: Mammalia, Order: Artiodactyla', ARRAY['mammalia', 'artiodactyla'], true),
  ('Pseudoryx nghetinhensis', 'taxonomy', 2, 'Family: Bovidae, Genus: Pseudoryx', ARRAY['bovidae', 'pseudoryx'], true),
  ('Pseudoryx nghetinhensis', 'morphology', 1, 'Long, straight, almost parallel horns and white markings on its face.', ARRAY['large_bodied', 'horns'], true),
  ('Pseudoryx nghetinhensis', 'morphology', 2, 'Primary color: Dark chocolate brown. Pattern: Bold white stripes and spots on the face.', ARRAY['brown_coloration', 'dark_coloration', 'white_markings'], true),
  ('Pseudoryx nghetinhensis', 'behavior', 1, 'So shy that no scientist has ever seen one in the wild.', ARRAY['elusive'], true),
  ('Pseudoryx nghetinhensis', 'behavior', 2, 'Has large scent glands on its face that it may use to mark its territory.', ARRAY['scent_marking'], true),
  ('Pseudoryx nghetinhensis', 'diet', 1, 'Diet type: Herbivore. Eats: leaves, especially from plants along forest streams.', ARRAY['herbivore', 'folivore'], true),
  ('Pseudoryx nghetinhensis', 'habitat', 1, 'Lives in wet, steep evergreen forests in the mountains.', ARRAY['forest', 'montane', 'tropical', 'terrestrial'], true),
  ('Pseudoryx nghetinhensis', 'habitat', 2, 'Prefers forest near rivers and streams.', ARRAY['riverine'], true),
  ('Pseudoryx nghetinhensis', 'geography', 1, 'Found only in the Annamite Mountains along the border of Vietnam and Laos.', ARRAY[]::text[], false),
  ('Pseudoryx nghetinhensis', 'reproduction', 1, 'Reproduction: Gives birth to live young. Young: 1 calf.', ARRAY['live_birth'], true),
  ('Pseudoryx nghetinhensis', 'conservation', 1, 'Status: Critically Endangered. Snares set for other animals are its biggest threat; it may be close to disappearing.', ARRAY[]::text[], false),
  ('Pseudoryx nghetinhensis', 'key_fact', 1, 'Scientists discovered it in 1992, one of the most surprising large-mammal finds of the 1900s.', ARRAY[]::text[], false),
  ('Pseudoryx nghetinhensis', 'key_fact', 2, 'It is nicknamed the ''Asian unicorn'' because it is so rare and hard to find.', ARRAY[]::text[], false),
  ('Pseudoryx nghetinhensis', 'key_fact', 3, 'Its name means ''spinning-wheel posts'' in a local language, after the shape of its horns.', ARRAY[]::text[], false),
  ('Equus grevyi', 'taxonomy', 1, 'Class: Mammalia, Order: Perissodactyla', ARRAY['mammalia', 'perissodactyla'], true),
  ('Equus grevyi', 'taxonomy', 2, 'Family: Equidae, Genus: Equus', ARRAY['equidae', 'equus'], true),
  ('Equus grevyi', 'morphology', 1, 'The largest wild member of the horse family, with big round ears and a tall, upright mane.', ARRAY['large_bodied', 'large_ears'], true),
  ('Equus grevyi', 'morphology', 2, 'Primary color: White. Pattern: Narrow black stripes that stop short of its white belly.', ARRAY['striped', 'white_markings', 'dark_coloration'], true),
  ('Equus grevyi', 'behavior', 1, 'Lives in loose herds whose members often change.', ARRAY['herd', 'social'], true),
  ('Equus grevyi', 'behavior', 2, 'Males guard large territories around water holes.', ARRAY['territorial'], true),
  ('Equus grevyi', 'diet', 1, 'Diet type: Herbivore. Eats: tough grasses that many other grazers cannot digest.', ARRAY['herbivore', 'grazer'], true),
  ('Equus grevyi', 'habitat', 1, 'Lives in dry grasslands and bushland.', ARRAY['arid', 'grassland', 'scrubland', 'terrestrial'], true),
  ('Equus grevyi', 'habitat', 2, 'Must stay within reach of water, though adults can go several days without drinking.', ARRAY['arid'], true),
  ('Equus grevyi', 'geography', 1, 'Found in northern Kenya and parts of Ethiopia.', ARRAY[]::text[], false),
  ('Equus grevyi', 'reproduction', 1, 'Reproduction: Gives birth to live young after about 13 months. Young: 1 foal. Lifespan: about 20 years', ARRAY['live_birth'], true),
  ('Equus grevyi', 'conservation', 1, 'Status: Endangered. Loss of grazing land and water to livestock, and hunting, have cut its numbers.', ARRAY[]::text[], false),
  ('Equus grevyi', 'key_fact', 1, 'Every zebra''s stripe pattern is unique, like a fingerprint.', ARRAY[]::text[], false),
  ('Equus grevyi', 'key_fact', 2, 'It is named after Jules Grévy, a French president who was given one as a gift.', ARRAY[]::text[], false),
  ('Equus grevyi', 'key_fact', 3, 'Its stripes are thinner and closer together than those of other zebras.', ARRAY[]::text[], false),
  ('Pongo abelii', 'taxonomy', 1, 'Class: Mammalia, Order: Primates', ARRAY['mammalia', 'primates'], true),
  ('Pongo abelii', 'taxonomy', 2, 'Family: Hominidae, Genus: Pongo', ARRAY['hominidae', 'pongo'], true),
  ('Pongo abelii', 'morphology', 1, 'A great ape with very long arms and shaggy hair; adult males grow cheek pads and a beard.', ARRAY['large_bodied', 'long_fur'], true),
  ('Pongo abelii', 'morphology', 2, 'Primary color: Pale orange-red. Pattern: Long, shaggy hair, lighter than its Bornean cousin''s.', ARRAY['red_coloration', 'brown_coloration'], true),
  ('Pongo abelii', 'behavior', 1, 'Builds a new sleeping nest of branches high in the trees every night.', ARRAY['nest_builder', 'climber'], true),
  ('Pongo abelii', 'behavior', 2, 'Mostly solitary; uses sticks as tools to get insects and seeds out of fruit.', ARRAY['tool_user', 'solitary'], true),
  ('Pongo abelii', 'diet', 1, 'Diet type: Omnivore (mostly fruit). Eats: fruit, especially figs, plus leaves, bark, insects and honey.', ARRAY['omnivore', 'frugivore', 'folivore', 'insect_eater'], true),
  ('Pongo abelii', 'habitat', 1, 'Lives in tropical rainforest, especially swamp and lowland forests.', ARRAY['forest', 'tropical', 'arboreal', 'wetland', 'terrestrial'], true),
  ('Pongo abelii', 'habitat', 2, 'Spends almost all its life in the trees and rarely comes down to the ground.', ARRAY['arboreal'], true),
  ('Pongo abelii', 'geography', 1, 'Found only in northern Sumatra, Indonesia.', ARRAY[]::text[], false),
  ('Pongo abelii', 'reproduction', 1, 'Reproduction: Gives birth to live young. Young: 1 about every 8 or 9 years. Lifespan: 50 years or more', ARRAY['live_birth'], true),
  ('Pongo abelii', 'conservation', 1, 'Status: Critically Endangered. Its forests are being cleared for palm oil farms and roads.', ARRAY[]::text[], false),
  ('Pongo abelii', 'key_fact', 1, 'Mothers have a baby only about once every 8 or 9 years, the longest gap of any mammal.', ARRAY[]::text[], false),
  ('Pongo abelii', 'key_fact', 2, 'Orangutan means ''person of the forest'' in the Malay language.', ARRAY[]::text[], false),
  ('Pongo abelii', 'key_fact', 3, 'Young orangutans stay with their mothers for years, learning which plants are good to eat.', ARRAY[]::text[], false),
  ('Loxodonta cyclotis', 'taxonomy', 1, 'Class: Mammalia, Order: Proboscidea', ARRAY['mammalia', 'proboscidea'], true),
  ('Loxodonta cyclotis', 'taxonomy', 2, 'Family: Elephantidae, Genus: Loxodonta', ARRAY['elephantidae', 'loxodonta'], true),
  ('Loxodonta cyclotis', 'morphology', 1, 'Smaller than the savanna elephant, with rounded ears and straight, downward-pointing tusks.', ARRAY['large_bodied', 'trunk', 'tusks'], true),
  ('Loxodonta cyclotis', 'morphology', 2, 'Primary color: Dark grey. Pattern: Often tinted reddish by the forest mud it bathes in.', ARRAY['grey_coloration', 'dark_coloration'], true),
  ('Loxodonta cyclotis', 'behavior', 1, 'Lives in small family groups led by a mother.', ARRAY['herd', 'social'], true),
  ('Loxodonta cyclotis', 'behavior', 2, 'Plants forest trees by spreading their seeds in its dung as it travels.', ARRAY['ecosystem_engineer', 'seed_disperser'], true),
  ('Loxodonta cyclotis', 'diet', 1, 'Diet type: Herbivore. Eats: leaves, bark and lots of fruit.', ARRAY['herbivore', 'folivore', 'frugivore'], true),
  ('Loxodonta cyclotis', 'habitat', 1, 'Lives in dense tropical rainforests.', ARRAY['forest', 'tropical', 'terrestrial'], true),
  ('Loxodonta cyclotis', 'habitat', 2, 'Visits forest clearings called bais to drink and to eat minerals from the soil.', ARRAY['wetland', 'freshwater'], true),
  ('Loxodonta cyclotis', 'geography', 1, 'Found in the rainforests of West and Central Africa, such as Gabon and the Republic of the Congo.', ARRAY[]::text[], false),
  ('Loxodonta cyclotis', 'reproduction', 1, 'Reproduction: Gives birth to live young after about 22 months. Young: 1 calf. Lifespan: about 60 years', ARRAY['live_birth', 'long_lived'], true),
  ('Loxodonta cyclotis', 'conservation', 1, 'Status: Critically Endangered. Poaching for ivory has cut its numbers by more than 80% in about 30 years.', ARRAY[]::text[], false),
  ('Loxodonta cyclotis', 'key_fact', 1, 'It was listed as its own species, separate from the savanna elephant, only in 2021.', ARRAY[]::text[], false),
  ('Loxodonta cyclotis', 'key_fact', 2, 'It is called the ''gardener of the forest'' because it spreads so many seeds.', ARRAY[]::text[], false),
  ('Loxodonta cyclotis', 'key_fact', 3, 'Its tusks are straighter and harder than a savanna elephant''s, which helps it move through thick forest.', ARRAY[]::text[], false),
  ('Marmota vancouverensis', 'taxonomy', 1, 'Class: Mammalia, Order: Rodentia', ARRAY['mammalia', 'rodentia'], true),
  ('Marmota vancouverensis', 'taxonomy', 2, 'Family: Sciuridae, Genus: Marmota', ARRAY['sciuridae', 'marmota'], true),
  ('Marmota vancouverensis', 'morphology', 1, 'A chubby, cat-sized ground squirrel with short legs and a bushy tail.', ARRAY['rounded_body', 'bushy_tail'], true),
  ('Marmota vancouverensis', 'morphology', 2, 'Primary color: Rich chocolate brown. Pattern: White patches on the nose, chin and chest.', ARRAY['brown_coloration', 'dark_coloration', 'white_markings'], true),
  ('Marmota vancouverensis', 'behavior', 1, 'Hibernates in its burrow for up to 7 months each year.', ARRAY['burrower', 'hibernator'], true),
  ('Marmota vancouverensis', 'behavior', 2, 'Lives in family colonies and whistles to warn others of danger.', ARRAY['social', 'vocal'], true),
  ('Marmota vancouverensis', 'diet', 1, 'Diet type: Herbivore. Eats: grasses, wildflowers and other mountain plants.', ARRAY['herbivore', 'grazer', 'folivore'], true),
  ('Marmota vancouverensis', 'habitat', 1, 'Lives in high mountain meadows above the forest.', ARRAY['montane', 'grassland', 'temperate', 'terrestrial'], true),
  ('Marmota vancouverensis', 'habitat', 2, 'Uses rocky slopes and boulders as lookouts and shelters.', ARRAY['rocky'], true),
  ('Marmota vancouverensis', 'geography', 1, 'Found only on Vancouver Island in British Columbia, Canada.', ARRAY[]::text[], false),
  ('Marmota vancouverensis', 'reproduction', 1, 'Reproduction: Gives birth to live young. Litter: 3 to 4 pups, usually every other year. Lifespan: about 10 years', ARRAY['live_birth', 'short_lived'], true),
  ('Marmota vancouverensis', 'conservation', 1, 'Status: Critically Endangered. Around 2003 fewer than 30 lived in the wild; breeding and release programs have helped.', ARRAY[]::text[], false),
  ('Marmota vancouverensis', 'key_fact', 1, 'It lives only on one island, and nowhere else on Earth.', ARRAY[]::text[], false),
  ('Marmota vancouverensis', 'key_fact', 2, 'It is one of the rarest mammals in North America.', ARRAY[]::text[], false),
  ('Marmota vancouverensis', 'key_fact', 3, 'While it hibernates, its body temperature drops to just a few degrees above freezing.', ARRAY[]::text[], false),
  ('Dendrolagus goodfellowi', 'taxonomy', 1, 'Class: Mammalia, Order: Diprotodontia', ARRAY['mammalia', 'diprotodontia'], true),
  ('Dendrolagus goodfellowi', 'taxonomy', 2, 'Family: Macropodidae, Genus: Dendrolagus', ARRAY['macropodidae', 'dendrolagus'], true),
  ('Dendrolagus goodfellowi', 'morphology', 1, 'A kangaroo built for climbing, with strong front legs, curved claws and a very long tail for balance.', ARRAY['long_claws', 'long_tail'], true),
  ('Dendrolagus goodfellowi', 'morphology', 2, 'Primary color: Chestnut red-brown. Pattern: Golden stripes down the back and a ringed tail.', ARRAY['red_coloration', 'brown_coloration', 'yellow_coloration', 'striped'], true),
  ('Dendrolagus goodfellowi', 'behavior', 1, 'Climbs trees easily and can hop down from high branches.', ARRAY['climber'], true),
  ('Dendrolagus goodfellowi', 'behavior', 2, 'Mostly solitary and quiet.', ARRAY['solitary'], true),
  ('Dendrolagus goodfellowi', 'diet', 1, 'Diet type: Herbivore. Eats: leaves, fruit, flowers and ferns.', ARRAY['herbivore', 'folivore', 'frugivore'], true),
  ('Dendrolagus goodfellowi', 'habitat', 1, 'Lives in tropical rainforest in the mountains.', ARRAY['forest', 'tropical', 'montane', 'arboreal', 'terrestrial'], true),
  ('Dendrolagus goodfellowi', 'habitat', 2, 'Spends most of its life high in the rainforest canopy.', ARRAY['arboreal'], true),
  ('Dendrolagus goodfellowi', 'geography', 1, 'Found in the mountain forests of Papua New Guinea.', ARRAY[]::text[], false),
  ('Dendrolagus goodfellowi', 'reproduction', 1, 'Reproduction: Gives birth to a tiny joey that grows in its mother''s pouch. Young: 1.', ARRAY['live_birth', 'pouch'], true),
  ('Dendrolagus goodfellowi', 'conservation', 1, 'Status: Endangered. Hunting and forest clearing threaten it.', ARRAY[]::text[], false),
  ('Dendrolagus goodfellowi', 'key_fact', 1, 'Tree-kangaroos come from ground kangaroos whose ancestors moved back into the trees.', ARRAY[]::text[], false),
  ('Dendrolagus goodfellowi', 'key_fact', 2, 'Tree-kangaroos can jump down to the ground from branches many metres up.', ARRAY[]::text[], false),
  ('Dendrolagus goodfellowi', 'key_fact', 3, 'Unlike ground kangaroos, it can move its back legs one at a time to walk along branches.', ARRAY[]::text[], false),
  ('Rhinoceros sondaicus', 'taxonomy', 1, 'Class: Mammalia, Order: Perissodactyla', ARRAY['mammalia', 'perissodactyla'], true),
  ('Rhinoceros sondaicus', 'taxonomy', 2, 'Family: Rhinocerotidae, Genus: Rhinoceros', ARRAY['rhinocerotidae', 'rhinoceros'], true),
  ('Rhinoceros sondaicus', 'morphology', 1, 'Huge body with one small horn and loose folds of skin that look like armor plates.', ARRAY['large_bodied', 'horns', 'skin_folds'], true),
  ('Rhinoceros sondaicus', 'morphology', 2, 'Primary color: Dusky grey. Pattern: Skin with a mosaic-like, scaly texture.', ARRAY['grey_coloration', 'rough_texture'], true),
  ('Rhinoceros sondaicus', 'behavior', 1, 'Solitary, except for mothers with calves.', ARRAY['solitary'], true),
  ('Rhinoceros sondaicus', 'behavior', 2, 'Wallows in mud to keep cool and protect its skin.', ARRAY['wallower'], true),
  ('Rhinoceros sondaicus', 'diet', 1, 'Diet type: Herbivore. Eats: leaves, young shoots, twigs and fallen fruit.', ARRAY['herbivore', 'folivore', 'frugivore'], true),
  ('Rhinoceros sondaicus', 'habitat', 1, 'Lives in lowland tropical rainforest with mud wallows.', ARRAY['forest', 'tropical', 'wetland', 'terrestrial'], true),
  ('Rhinoceros sondaicus', 'habitat', 2, 'Stays close to water and swampy ground.', ARRAY['freshwater', 'wetland', 'muddy_substrate'], true),
  ('Rhinoceros sondaicus', 'geography', 1, 'Found only in Ujung Kulon National Park, at the western tip of Java, Indonesia.', ARRAY[]::text[], false),
  ('Rhinoceros sondaicus', 'reproduction', 1, 'Reproduction: Gives birth to live young after about 16 months. Young: 1 calf. Lifespan: about 30 to 40 years', ARRAY['live_birth'], true),
  ('Rhinoceros sondaicus', 'conservation', 1, 'Status: Critically Endangered. Fewer than 80 remain, all in one national park.', ARRAY[]::text[], false),
  ('Rhinoceros sondaicus', 'key_fact', 1, 'Every Javan rhino left in the world lives in a single national park.', ARRAY[]::text[], false),
  ('Rhinoceros sondaicus', 'key_fact', 2, 'Females often have no horn at all.', ARRAY[]::text[], false),
  ('Rhinoceros sondaicus', 'key_fact', 3, 'It is one of the rarest large mammals on Earth.', ARRAY[]::text[], false),
  ('Pteropus livingstonii', 'taxonomy', 1, 'Class: Mammalia, Order: Chiroptera', ARRAY['mammalia', 'chiroptera'], true),
  ('Pteropus livingstonii', 'taxonomy', 2, 'Family: Pteropodidae, Genus: Pteropus', ARRAY['pteropodidae', 'pteropus'], true),
  ('Pteropus livingstonii', 'morphology', 1, 'A big fruit bat with wings about 1.4 m across, a fox-like face and large eyes.', ARRAY['wings', 'large_eyes'], true),
  ('Pteropus livingstonii', 'morphology', 2, 'Primary color: Black. Pattern: Some have golden or orange fur patches.', ARRAY['dark_coloration', 'yellow_coloration'], true),
  ('Pteropus livingstonii', 'behavior', 1, 'Roosts in groups in tall trees on steep, forested slopes.', ARRAY['social', 'flier'], true),
  ('Pteropus livingstonii', 'behavior', 2, 'Soars on rising warm air like a bird of prey, which is rare for bats.', ARRAY['flier'], true),
  ('Pteropus livingstonii', 'diet', 1, 'Diet type: Herbivore. Eats: fruit, flowers, nectar and pollen.', ARRAY['herbivore', 'frugivore'], true),
  ('Pteropus livingstonii', 'habitat', 1, 'Lives in mountain rainforest and cloud forest.', ARRAY['forest', 'montane', 'tropical', 'arboreal'], true),
  ('Pteropus livingstonii', 'habitat', 2, 'Roosts on steep, wet slopes high up in the forest.', ARRAY['montane'], true),
  ('Pteropus livingstonii', 'geography', 1, 'Found only on the islands of Anjouan and Mohéli in the Comoros, between Africa and Madagascar.', ARRAY[]::text[], false),
  ('Pteropus livingstonii', 'reproduction', 1, 'Reproduction: Gives birth to live young. Young: 1 pup a year.', ARRAY['live_birth'], true),
  ('Pteropus livingstonii', 'conservation', 1, 'Status: Endangered. Forest clearing on its two small islands threatens its roosts.', ARRAY[]::text[], false),
  ('Pteropus livingstonii', 'key_fact', 1, 'It is one of the largest bats in the world.', ARRAY[]::text[], false),
  ('Pteropus livingstonii', 'key_fact', 2, 'It spreads seeds and pollen, helping its island forests grow.', ARRAY[]::text[], false),
  ('Pteropus livingstonii', 'key_fact', 3, 'It is named after the explorer David Livingstone.', ARRAY[]::text[], false),
  ('Rhynchocyon chrysopygus', 'taxonomy', 1, 'Class: Mammalia, Order: Macroscelidea', ARRAY['mammalia', 'macroscelidea'], true),
  ('Rhynchocyon chrysopygus', 'taxonomy', 2, 'Family: Macroscelididae, Genus: Rhynchocyon', ARRAY['macroscelididae', 'rhynchocyon'], true),
  ('Rhynchocyon chrysopygus', 'morphology', 1, 'Rat-sized, with long thin legs and a long, bendy, trunk-like nose.', ARRAY['specialized_snout', 'slender'], true),
  ('Rhynchocyon chrysopygus', 'morphology', 2, 'Primary color: Reddish brown. Pattern: A bright golden patch on its rump.', ARRAY['red_coloration', 'brown_coloration', 'yellow_coloration'], true),
  ('Rhynchocyon chrysopygus', 'behavior', 1, 'Active by day, searching the leaf litter with its twitching nose.', ARRAY['diurnal'], true),
  ('Rhynchocyon chrysopygus', 'behavior', 2, 'Lives in pairs that share a territory.', ARRAY['territorial'], true),
  ('Rhynchocyon chrysopygus', 'diet', 1, 'Diet type: Insectivore. Eats: beetles, ants, termites, earthworms and spiders.', ARRAY['insect_eater', 'carnivore', 'vermivore'], true),
  ('Rhynchocyon chrysopygus', 'habitat', 1, 'Lives on the floor of dry coastal forests.', ARRAY['forest', 'coastal', 'tropical', 'terrestrial'], true),
  ('Rhynchocyon chrysopygus', 'habitat', 2, 'Builds nests of dead leaves on the forest floor to rest in.', ARRAY['forest'], true),
  ('Rhynchocyon chrysopygus', 'geography', 1, 'Found only in coastal forests of Kenya, such as Arabuko-Sokoke Forest.', ARRAY[]::text[], false),
  ('Rhynchocyon chrysopygus', 'reproduction', 1, 'Reproduction: Gives birth to live young. Young: 1 at a time, several times a year. Lifespan: about 4 to 5 years', ARRAY['live_birth', 'short_lived'], true),
  ('Rhynchocyon chrysopygus', 'conservation', 1, 'Status: Endangered. Its small forests are being cleared and broken up.', ARRAY[]::text[], false),
  ('Rhynchocyon chrysopygus', 'key_fact', 1, 'Sengis are more closely related to elephants than to shrews.', ARRAY[]::text[], false),
  ('Rhynchocyon chrysopygus', 'key_fact', 2, 'The golden patch may trick predators into going for its thick-skinned rump instead of its head.', ARRAY[]::text[], false),
  ('Rhynchocyon chrysopygus', 'key_fact', 3, 'It is also called the golden-rumped elephant shrew.', ARRAY[]::text[], false),
  ('Ochotona iliensis', 'taxonomy', 1, 'Class: Mammalia, Order: Lagomorpha', ARRAY['mammalia', 'lagomorpha'], true),
  ('Ochotona iliensis', 'taxonomy', 2, 'Family: Ochotonidae, Genus: Ochotona', ARRAY['ochotonidae', 'ochotona'], true),
  ('Ochotona iliensis', 'morphology', 1, 'Small, round and tailless, with rounded ears; a relative of rabbits.', ARRAY['tiny', 'rounded_body'], true),
  ('Ochotona iliensis', 'morphology', 2, 'Primary color: Grey. Pattern: Rusty red spots on the forehead and neck.', ARRAY['grey_coloration', 'red_coloration', 'spotted'], true),
  ('Ochotona iliensis', 'behavior', 1, 'Stores dried plants as ''haypiles'' in rock cracks to eat in winter.', ARRAY['food_storer'], true),
  ('Ochotona iliensis', 'behavior', 2, 'Lives alone and is very quiet, unlike most pikas.', ARRAY['solitary'], true),
  ('Ochotona iliensis', 'diet', 1, 'Diet type: Herbivore. Eats: mountain grasses and herbs.', ARRAY['herbivore', 'grazer', 'folivore'], true),
  ('Ochotona iliensis', 'habitat', 1, 'Lives on rocky cliffs high in the mountains.', ARRAY['montane', 'rocky', 'terrestrial'], true),
  ('Ochotona iliensis', 'habitat', 2, 'Found at 2,800 to 4,100 m above sea level.', ARRAY['montane'], true),
  ('Ochotona iliensis', 'geography', 1, 'Found only in the Tian Shan mountains of Xinjiang, China.', ARRAY[]::text[], false),
  ('Ochotona iliensis', 'reproduction', 1, 'Reproduction: Gives birth to live young. Lifespan: probably only a few years', ARRAY['live_birth', 'short_lived'], true),
  ('Ochotona iliensis', 'conservation', 1, 'Status: Endangered. Fewer than 1,000 may remain as warming pushes it higher up the mountains.', ARRAY[]::text[], false),
  ('Ochotona iliensis', 'key_fact', 1, 'It was discovered in 1983 by a scientist who then spent years searching to see it again.', ARRAY[]::text[], false),
  ('Ochotona iliensis', 'key_fact', 2, 'It is nicknamed the ''magic rabbit'' because it is so rarely seen.', ARRAY[]::text[], false),
  ('Ochotona iliensis', 'key_fact', 3, 'As the climate warms, it is moving higher up the mountains, where there is less room.', ARRAY[]::text[], false),
  ('Sarcophilus harrisii', 'taxonomy', 1, 'Class: Mammalia, Order: Dasyuromorphia', ARRAY['mammalia', 'dasyuromorphia'], true),
  ('Sarcophilus harrisii', 'taxonomy', 2, 'Family: Dasyuridae, Genus: Sarcophilus', ARRAY['dasyuridae', 'sarcophilus'], true),
  ('Sarcophilus harrisii', 'morphology', 1, 'Stocky, dog-sized body with a large head, strong jaws and a thick tail.', ARRAY['robust'], true),
  ('Sarcophilus harrisii', 'morphology', 2, 'Primary color: Black. Pattern: A white stripe or patch across the chest.', ARRAY['dark_coloration', 'white_markings'], true),
  ('Sarcophilus harrisii', 'behavior', 1, 'Active at night and makes loud screeches and growls, especially at meals.', ARRAY['nocturnal', 'vocal'], true),
  ('Sarcophilus harrisii', 'behavior', 2, 'Mostly solitary, though several devils may gather at one big meal.', ARRAY['solitary'], true),
  ('Sarcophilus harrisii', 'diet', 1, 'Diet type: Carnivore. Eats: mostly carrion, plus small animals; it eats the bones and fur too.', ARRAY['carnivore', 'scavenger'], true),
  ('Sarcophilus harrisii', 'habitat', 1, 'Lives in forests, woodlands and coastal scrub.', ARRAY['forest', 'scrubland', 'coastal', 'temperate', 'terrestrial'], true),
  ('Sarcophilus harrisii', 'habitat', 2, 'Rests by day in dens, hollow logs and burrows.', ARRAY['burrower_habitat'], true),
  ('Sarcophilus harrisii', 'geography', 1, 'Found in the wild only on the island of Tasmania, Australia.', ARRAY[]::text[], false),
  ('Sarcophilus harrisii', 'reproduction', 1, 'Reproduction: Gives birth to tiny babies that grow in a pouch. Litter: up to 4 joeys. Lifespan: about 5 years', ARRAY['live_birth', 'pouch', 'short_lived'], true),
  ('Sarcophilus harrisii', 'conservation', 1, 'Status: Endangered. A spreading disease has greatly reduced wild devil numbers.', ARRAY[]::text[], false),
  ('Sarcophilus harrisii', 'key_fact', 1, 'For its size, it has one of the strongest bites of any mammal.', ARRAY[]::text[], false),
  ('Sarcophilus harrisii', 'key_fact', 2, 'It is the largest meat-eating marsupial alive today.', ARRAY[]::text[], false),
  ('Sarcophilus harrisii', 'key_fact', 3, 'Its ears turn red when it is excited or upset.', ARRAY[]::text[], false),
  ('Solenodon paradoxus', 'taxonomy', 1, 'Class: Mammalia, Order: Eulipotyphla', ARRAY['mammalia', 'eulipotyphla'], true),
  ('Solenodon paradoxus', 'taxonomy', 2, 'Family: Solenodontidae, Genus: Solenodon', ARRAY['solenodontidae', 'solenodon'], true),
  ('Solenodon paradoxus', 'morphology', 1, 'Shrew-like, with a long bendy snout, tiny eyes, big claws and a bare, scaly tail.', ARRAY['specialized_snout', 'long_claws'], true),
  ('Solenodon paradoxus', 'morphology', 2, 'Primary color: Dark brown. Pattern: Paler, reddish fur on the face.', ARRAY['brown_coloration', 'dark_coloration', 'red_coloration'], true),
  ('Solenodon paradoxus', 'behavior', 1, 'Active at night, rooting through soil and leaf litter with its snout.', ARRAY['nocturnal', 'burrower'], true),
  ('Solenodon paradoxus', 'behavior', 2, 'One of the few venomous mammals; its venom flows along grooves in its teeth.', ARRAY['venomous'], true),
  ('Solenodon paradoxus', 'diet', 1, 'Diet type: Insectivore. Eats: insects, spiders, worms and other small animals.', ARRAY['insect_eater', 'carnivore', 'vermivore'], true),
  ('Solenodon paradoxus', 'habitat', 1, 'Lives in forests and scrub, often on rocky limestone ground.', ARRAY['forest', 'scrubland', 'rocky', 'tropical', 'terrestrial'], true),
  ('Solenodon paradoxus', 'habitat', 2, 'Shelters in caves, hollow logs and burrows.', ARRAY['burrower_habitat'], true),
  ('Solenodon paradoxus', 'geography', 1, 'Found only on the island of Hispaniola, shared by Haiti and the Dominican Republic.', ARRAY[]::text[], false),
  ('Solenodon paradoxus', 'reproduction', 1, 'Reproduction: Gives birth to live young. Litter: 1 to 2. Lifespan: about 11 years', ARRAY['live_birth', 'short_lived'], true),
  ('Solenodon paradoxus', 'conservation', 1, 'Status: Least Concern. Still found across much of Hispaniola, but forest loss and pet dogs and cats are a danger.', ARRAY[]::text[], false),
  ('Solenodon paradoxus', 'key_fact', 1, 'Its name means ''grooved tooth'', after the teeth that carry its venom.', ARRAY[]::text[], false),
  ('Solenodon paradoxus', 'key_fact', 2, 'Its family is ancient: its ancestors split from other mammals while dinosaurs still lived.', ARRAY[]::text[], false),
  ('Solenodon paradoxus', 'key_fact', 3, 'It walks with a wobbly zigzag and sometimes trips over its own feet.', ARRAY[]::text[], false)
) AS v(scientific_name, category, reveal_order, label, tags, is_filtering)
JOIN species s ON s.scientific_name = v.scientific_name
ON CONFLICT (species_id, category, reveal_order) DO NOTHING;

INSERT INTO species_facts (species_id, category, sort_order, fact_text)
SELECT s.id, v.category, v.sort_order, v.fact_text
FROM (VALUES
  ('Daubentonia madagascariensis', 'life_description', 1, 'A young aye-aye stays with its mother for about two years while it learns to find food.'),
  ('Daubentonia madagascariensis', 'threat', 1, 'Forest clearing for farming; hunting; old beliefs that it is bad luck'),
  ('Manis javanica', 'life_description', 1, 'A baby pangolin clings to its mother''s tail and rides along as she searches for food.'),
  ('Manis javanica', 'threat', 1, 'Illegal hunting and trade for scales and meat; forest loss'),
  ('Mustela nigripes', 'life_description', 1, 'Kits are born underground in spring and first peek out of the burrow in summer.'),
  ('Mustela nigripes', 'threat', 1, 'Loss of prairie dog towns; sylvatic plague disease; plowing of grasslands'),
  ('Zaglossus bruijnii', 'life_description', 1, 'The puggle hatches in its mother''s pouch and stays there until its spines start to grow.'),
  ('Zaglossus bruijnii', 'threat', 1, 'Hunting with dogs; forest clearing; mining and new roads'),
  ('Elephas maximus', 'life_description', 1, 'A calf can stand within an hour of birth and drinks its mother''s milk for several years.'),
  ('Elephas maximus', 'threat', 1, 'Forest loss; conflict with farmers; poaching for ivory and skin'),
  ('Okapia johnstoni', 'life_description', 1, 'A newborn calf hides in a nest in the undergrowth for its first weeks.'),
  ('Okapia johnstoni', 'threat', 1, 'Forest clearing for mining and farming; hunting; unrest in the region'),
  ('Bradypus pygmaeus', 'life_description', 1, 'A baby sloth clings to its mother''s belly for months as she moves through the mangroves.'),
  ('Bradypus pygmaeus', 'threat', 1, 'Cutting of mangroves; visitors disturbing the island; a very small range'),
  ('Lasiorhinus krefftii', 'life_description', 1, 'A joey lives in its mother''s pouch for about 8 to 9 months.'),
  ('Lasiorhinus krefftii', 'threat', 1, 'Very small population in few places; drought and fire; competition with cattle for grass'),
  ('Cryptochloris wintoni', 'threat', 1, 'Diamond mining in coastal dunes; building and roads along the coast'),
  ('Canis simensis', 'life_description', 1, 'Pups are born in a den, and the whole pack helps feed them.'),
  ('Canis simensis', 'threat', 1, 'Diseases from domestic dogs; farming and grazing in the highlands'),
  ('Rhinopithecus roxellana', 'life_description', 1, 'Babies are born in spring and stay close to their mothers for their first year.'),
  ('Rhinopithecus roxellana', 'threat', 1, 'Logging; past hunting; roads and tourism in its forests'),
  ('Ailurus fulgens', 'life_description', 1, 'Cubs are born in tree hollows or rock crevices and stay in the nest for about three months.'),
  ('Ailurus fulgens', 'threat', 1, 'Forest clearing; loss of bamboo; poaching and illegal pet trade'),
  ('Priodontes maximus', 'threat', 1, 'Hunting for meat; forests and savannas cleared for farms'),
  ('Macrotis lagotis', 'life_description', 1, 'Joeys stay in the pouch for about 80 days.'),
  ('Macrotis lagotis', 'threat', 1, 'Feral cats and foxes; wildfires; competition with rabbits and grazing animals'),
  ('Pseudoryx nghetinhensis', 'threat', 1, 'Wire snares set in the forest; forest loss; roads through its mountains'),
  ('Equus grevyi', 'life_description', 1, 'A foal can walk within an hour of being born.'),
  ('Equus grevyi', 'threat', 1, 'Competition with livestock for grass and water; hunting; drought'),
  ('Pongo abelii', 'life_description', 1, 'Babies cling to their mothers and drink their milk for several years.'),
  ('Pongo abelii', 'threat', 1, 'Forest clearing for palm oil and farms; roads; illegal pet trade'),
  ('Loxodonta cyclotis', 'life_description', 1, 'Calves are cared for by the whole family group.'),
  ('Loxodonta cyclotis', 'threat', 1, 'Poaching for ivory and meat; logging roads; forest loss'),
  ('Marmota vancouverensis', 'life_description', 1, 'Pups first come out of the burrow in early summer, about a month after they are born.'),
  ('Marmota vancouverensis', 'threat', 1, 'Very small population; predators such as wolves, cougars and eagles; changing mountain meadows'),
  ('Dendrolagus goodfellowi', 'life_description', 1, 'A joey lives in the pouch for about 10 months.'),
  ('Dendrolagus goodfellowi', 'threat', 1, 'Hunting; forest clearing for farming and logging'),
  ('Rhinoceros sondaicus', 'life_description', 1, 'A calf stays with its mother for about two years.'),
  ('Rhinoceros sondaicus', 'threat', 1, 'Poaching for its horn; volcano and tsunami risk; all the rhinos living in one place'),
  ('Pteropus livingstonii', 'life_description', 1, 'A mother carries her pup while it is small, then leaves it at the roost while she feeds.'),
  ('Pteropus livingstonii', 'threat', 1, 'Forest clearing for farms; cutting of roost trees; cyclones'),
  ('Rhynchocyon chrysopygus', 'life_description', 1, 'Young are born in a leaf nest and grow up fast, leaving their parents within weeks.'),
  ('Rhynchocyon chrysopygus', 'threat', 1, 'Forest clearing; logging; snares'),
  ('Ochotona iliensis', 'threat', 1, 'Warming climate; livestock grazing; its tiny, scattered range'),
  ('Sarcophilus harrisii', 'life_description', 1, 'Newborns are the size of a grain of rice and crawl into the pouch.'),
  ('Sarcophilus harrisii', 'threat', 1, 'A spreading facial tumor disease; cars on roads at night'),
  ('Solenodon paradoxus', 'life_description', 1, 'Young follow their mother closely for months, learning where to find food.'),
  ('Solenodon paradoxus', 'threat', 1, 'Forest clearing; dogs, cats and mongooses brought by people')
) AS v(scientific_name, category, sort_order, fact_text)
JOIN species s ON s.scientific_name = v.scientific_name
ON CONFLICT (species_id, category, sort_order) DO NOTHING;

COMMIT;
