// Regions and continents for every country, so questions can ask "Does it live
// in East Africa?". From Natural Earth's UN regions (natural_earth.countries
// subregion and continent), with kid-friendly names. Checked in, so the content
// build needs no database. Regenerate with:
//   SELECT adm0_a3, iso_a2, name, subregion, continent FROM natural_earth.countries
// (Natural Earth leaves iso_a2 empty for France, Norway, Taiwan and Kosovo; filled in by hand.)

export type ContinentKey = 'africa' | 'asia' | 'europe' | 'north-america' | 'south-america' | 'oceania';

export const CONTINENT_NAMES: Record<ContinentKey, string> = {
  africa: 'Africa', asia: 'Asia', europe: 'Europe', 'north-america': 'North America', 'south-america': 'South America', oceania: 'Oceania',
};

export const REGIONS: Record<string, { name: string; continent: ContinentKey }> = {
  'east-africa': { name: 'East Africa', continent: 'africa' },
  'central-africa': { name: 'Central Africa', continent: 'africa' },
  'north-africa': { name: 'North Africa', continent: 'africa' },
  'southern-africa': { name: 'Southern Africa', continent: 'africa' },
  'west-africa': { name: 'West Africa', continent: 'africa' },
  'central-asia': { name: 'Central Asia', continent: 'asia' },
  'east-asia': { name: 'East Asia', continent: 'asia' },
  'southeast-asia': { name: 'Southeast Asia', continent: 'asia' },
  'south-asia': { name: 'South Asia', continent: 'asia' },
  'west-asia': { name: 'West Asia (the Middle East)', continent: 'asia' },
  'eastern-europe': { name: 'Eastern Europe', continent: 'europe' },
  'northern-europe': { name: 'Northern Europe', continent: 'europe' },
  'southern-europe': { name: 'Southern Europe', continent: 'europe' },
  'western-europe': { name: 'Western Europe', continent: 'europe' },
  'caribbean': { name: 'the Caribbean islands', continent: 'north-america' },
  'central-america': { name: 'Central America and Mexico', continent: 'north-america' },
  'usa-canada': { name: 'the USA and Canada', continent: 'north-america' },
  'south-america': { name: 'South America', continent: 'south-america' },
  'australia-nz': { name: 'Australia and New Zealand', continent: 'oceania' },
  'melanesia': { name: 'New Guinea and nearby islands', continent: 'oceania' },
  'micronesia': { name: 'the islands of Micronesia', continent: 'oceania' },
  'polynesia': { name: 'the islands of Polynesia', continent: 'oceania' },
};

/** [Natural Earth adm0_a3 (the ISO alpha-3 code, except the aliases below), ISO alpha-2 ('' when none), region key, name]. */
const COUNTRY_REGIONS: ReadonlyArray<readonly [string, string, string, string]> = [
  ['ATC', '', 'australia-nz', 'Ashmore and Cartier Is.'],
  ['AUS', 'AU', 'australia-nz', 'Australia'],
  ['CSI', '', 'australia-nz', 'Coral Sea Is.'],
  ['NFK', 'NF', 'australia-nz', 'Norfolk Island'],
  ['NZL', 'NZ', 'australia-nz', 'New Zealand'],
  ['ABW', 'AW', 'caribbean', 'Aruba'],
  ['AIA', 'AI', 'caribbean', 'Anguilla'],
  ['ATG', 'AG', 'caribbean', 'Antigua and Barb.'],
  ['BHS', 'BS', 'caribbean', 'Bahamas'],
  ['BJN', '', 'caribbean', 'Bajo Nuevo Bank'],
  ['BLM', 'BL', 'caribbean', 'St-Barthélemy'],
  ['BRB', 'BB', 'caribbean', 'Barbados'],
  ['CUB', 'CU', 'caribbean', 'Cuba'],
  ['CUW', 'CW', 'caribbean', 'Curaçao'],
  ['CYM', 'KY', 'caribbean', 'Cayman Is.'],
  ['DMA', 'DM', 'caribbean', 'Dominica'],
  ['DOM', 'DO', 'caribbean', 'Dominican Rep.'],
  ['GRD', 'GD', 'caribbean', 'Grenada'],
  ['HTI', 'HT', 'caribbean', 'Haiti'],
  ['JAM', 'JM', 'caribbean', 'Jamaica'],
  ['KNA', 'KN', 'caribbean', 'St. Kitts and Nevis'],
  ['LCA', 'LC', 'caribbean', 'Saint Lucia'],
  ['MAF', 'MF', 'caribbean', 'St-Martin'],
  ['MSR', 'MS', 'caribbean', 'Montserrat'],
  ['PRI', 'PR', 'caribbean', 'Puerto Rico'],
  ['SER', '', 'caribbean', 'Serranilla Bank'],
  ['SXM', 'SX', 'caribbean', 'Sint Maarten'],
  ['TCA', 'TC', 'caribbean', 'Turks and Caicos Is.'],
  ['TTO', 'TT', 'caribbean', 'Trinidad and Tobago'],
  ['USG', '', 'caribbean', 'USNB Guantanamo Bay'],
  ['VCT', 'VC', 'caribbean', 'St. Vin. and Gren.'],
  ['VGB', 'VG', 'caribbean', 'British Virgin Is.'],
  ['VIR', 'VI', 'caribbean', 'U.S. Virgin Is.'],
  ['AGO', 'AO', 'central-africa', 'Angola'],
  ['CAF', 'CF', 'central-africa', 'Central African Rep.'],
  ['CMR', 'CM', 'central-africa', 'Cameroon'],
  ['COD', 'CD', 'central-africa', 'Dem. Rep. Congo'],
  ['COG', 'CG', 'central-africa', 'Congo'],
  ['GAB', 'GA', 'central-africa', 'Gabon'],
  ['GNQ', 'GQ', 'central-africa', 'Eq. Guinea'],
  ['STP', 'ST', 'central-africa', 'São Tomé and Principe'],
  ['TCD', 'TD', 'central-africa', 'Chad'],
  ['BLZ', 'BZ', 'central-america', 'Belize'],
  ['CRI', 'CR', 'central-america', 'Costa Rica'],
  ['GTM', 'GT', 'central-america', 'Guatemala'],
  ['HND', 'HN', 'central-america', 'Honduras'],
  ['MEX', 'MX', 'central-america', 'Mexico'],
  ['NIC', 'NI', 'central-america', 'Nicaragua'],
  ['PAN', 'PA', 'central-america', 'Panama'],
  ['SLV', 'SV', 'central-america', 'El Salvador'],
  ['KAB', '', 'central-asia', 'Baikonur'],
  ['KAZ', 'KZ', 'central-asia', 'Kazakhstan'],
  ['KGZ', 'KG', 'central-asia', 'Kyrgyzstan'],
  ['TJK', 'TJ', 'central-asia', 'Tajikistan'],
  ['TKM', 'TM', 'central-asia', 'Turkmenistan'],
  ['UZB', 'UZ', 'central-asia', 'Uzbekistan'],
  ['BDI', 'BI', 'east-africa', 'Burundi'],
  ['COM', 'KM', 'east-africa', 'Comoros'],
  ['DJI', 'DJ', 'east-africa', 'Djibouti'],
  ['ERI', 'ER', 'east-africa', 'Eritrea'],
  ['ETH', 'ET', 'east-africa', 'Ethiopia'],
  ['KEN', 'KE', 'east-africa', 'Kenya'],
  ['MDG', 'MG', 'east-africa', 'Madagascar'],
  ['MOZ', 'MZ', 'east-africa', 'Mozambique'],
  ['MWI', 'MW', 'east-africa', 'Malawi'],
  ['RWA', 'RW', 'east-africa', 'Rwanda'],
  ['SDS', 'SS', 'east-africa', 'S. Sudan'],
  ['SOL', '', 'east-africa', 'Somaliland'],
  ['SOM', 'SO', 'east-africa', 'Somalia'],
  ['TZA', 'TZ', 'east-africa', 'Tanzania'],
  ['UGA', 'UG', 'east-africa', 'Uganda'],
  ['ZMB', 'ZM', 'east-africa', 'Zambia'],
  ['ZWE', 'ZW', 'east-africa', 'Zimbabwe'],
  ['CHN', 'CN', 'east-asia', 'China'],
  ['HKG', 'HK', 'east-asia', 'Hong Kong'],
  ['JPN', 'JP', 'east-asia', 'Japan'],
  ['KOR', 'KR', 'east-asia', 'South Korea'],
  ['MAC', 'MO', 'east-asia', 'Macao'],
  ['MNG', 'MN', 'east-asia', 'Mongolia'],
  ['PRK', 'KP', 'east-asia', 'North Korea'],
  ['TWN', 'TW', 'east-asia', 'Taiwan'],
  ['BGR', 'BG', 'eastern-europe', 'Bulgaria'],
  ['BLR', 'BY', 'eastern-europe', 'Belarus'],
  ['CZE', 'CZ', 'eastern-europe', 'Czechia'],
  ['HUN', 'HU', 'eastern-europe', 'Hungary'],
  ['MDA', 'MD', 'eastern-europe', 'Moldova'],
  ['POL', 'PL', 'eastern-europe', 'Poland'],
  ['ROU', 'RO', 'eastern-europe', 'Romania'],
  ['RUS', 'RU', 'eastern-europe', 'Russia'],
  ['SVK', 'SK', 'eastern-europe', 'Slovakia'],
  ['UKR', 'UA', 'eastern-europe', 'Ukraine'],
  ['FJI', 'FJ', 'melanesia', 'Fiji'],
  ['NCL', 'NC', 'melanesia', 'New Caledonia'],
  ['PNG', 'PG', 'melanesia', 'Papua New Guinea'],
  ['SLB', 'SB', 'melanesia', 'Solomon Is.'],
  ['VUT', 'VU', 'melanesia', 'Vanuatu'],
  ['FSM', 'FM', 'micronesia', 'Micronesia'],
  ['GUM', 'GU', 'micronesia', 'Guam'],
  ['KIR', 'KI', 'micronesia', 'Kiribati'],
  ['MHL', 'MH', 'micronesia', 'Marshall Is.'],
  ['MNP', 'MP', 'micronesia', 'N. Mariana Is.'],
  ['NRU', 'NR', 'micronesia', 'Nauru'],
  ['PLW', 'PW', 'micronesia', 'Palau'],
  ['BRT', '', 'north-africa', 'Bir Tawil'],
  ['DZA', 'DZ', 'north-africa', 'Algeria'],
  ['EGY', 'EG', 'north-africa', 'Egypt'],
  ['LBY', 'LY', 'north-africa', 'Libya'],
  ['MAR', 'MA', 'north-africa', 'Morocco'],
  ['SAH', 'EH', 'north-africa', 'W. Sahara'],
  ['SDN', 'SD', 'north-africa', 'Sudan'],
  ['TUN', 'TN', 'north-africa', 'Tunisia'],
  ['ALD', 'AX', 'northern-europe', 'Åland'],
  ['DNK', 'DK', 'northern-europe', 'Denmark'],
  ['EST', 'EE', 'northern-europe', 'Estonia'],
  ['FIN', 'FI', 'northern-europe', 'Finland'],
  ['FRO', 'FO', 'northern-europe', 'Faeroe Is.'],
  ['GBR', 'GB', 'northern-europe', 'United Kingdom'],
  ['GGY', 'GG', 'northern-europe', 'Guernsey'],
  ['IMN', 'IM', 'northern-europe', 'Isle of Man'],
  ['IRL', 'IE', 'northern-europe', 'Ireland'],
  ['ISL', 'IS', 'northern-europe', 'Iceland'],
  ['JEY', 'JE', 'northern-europe', 'Jersey'],
  ['LTU', 'LT', 'northern-europe', 'Lithuania'],
  ['LVA', 'LV', 'northern-europe', 'Latvia'],
  ['NOR', 'NO', 'northern-europe', 'Norway'],
  ['SWE', 'SE', 'northern-europe', 'Sweden'],
  ['ASM', 'AS', 'polynesia', 'American Samoa'],
  ['COK', 'CK', 'polynesia', 'Cook Is.'],
  ['NIU', 'NU', 'polynesia', 'Niue'],
  ['PCN', 'PN', 'polynesia', 'Pitcairn Is.'],
  ['PYF', 'PF', 'polynesia', 'Fr. Polynesia'],
  ['TON', 'TO', 'polynesia', 'Tonga'],
  ['TUV', 'TV', 'polynesia', 'Tuvalu'],
  ['WLF', 'WF', 'polynesia', 'Wallis and Futuna Is.'],
  ['WSM', 'WS', 'polynesia', 'Samoa'],
  ['ARG', 'AR', 'south-america', 'Argentina'],
  ['BOL', 'BO', 'south-america', 'Bolivia'],
  ['BRA', 'BR', 'south-america', 'Brazil'],
  ['BRI', '', 'south-america', 'Brazilian I.'],
  ['CHL', 'CL', 'south-america', 'Chile'],
  ['COL', 'CO', 'south-america', 'Colombia'],
  ['ECU', 'EC', 'south-america', 'Ecuador'],
  ['FLK', 'FK', 'south-america', 'Falkland Is.'],
  ['GUY', 'GY', 'south-america', 'Guyana'],
  ['PER', 'PE', 'south-america', 'Peru'],
  ['PRY', 'PY', 'south-america', 'Paraguay'],
  ['SPI', '', 'south-america', 'Southern Patagonian Ice Field'],
  ['SUR', 'SR', 'south-america', 'Suriname'],
  ['URY', 'UY', 'south-america', 'Uruguay'],
  ['VEN', 'VE', 'south-america', 'Venezuela'],
  ['AFG', 'AF', 'south-asia', 'Afghanistan'],
  ['BGD', 'BD', 'south-asia', 'Bangladesh'],
  ['BTN', 'BT', 'south-asia', 'Bhutan'],
  ['IND', 'IN', 'south-asia', 'India'],
  ['IRN', 'IR', 'south-asia', 'Iran'],
  ['KAS', '', 'south-asia', 'Siachen Glacier'],
  ['LKA', 'LK', 'south-asia', 'Sri Lanka'],
  ['NPL', 'NP', 'south-asia', 'Nepal'],
  ['PAK', 'PK', 'south-asia', 'Pakistan'],
  ['BRN', 'BN', 'southeast-asia', 'Brunei'],
  ['IDN', 'ID', 'southeast-asia', 'Indonesia'],
  ['KHM', 'KH', 'southeast-asia', 'Cambodia'],
  ['LAO', 'LA', 'southeast-asia', 'Laos'],
  ['MMR', 'MM', 'southeast-asia', 'Myanmar'],
  ['MYS', 'MY', 'southeast-asia', 'Malaysia'],
  ['PGA', '', 'southeast-asia', 'Spratly Is.'],
  ['PHL', 'PH', 'southeast-asia', 'Philippines'],
  ['SCR', '', 'southeast-asia', 'Scarborough Reef'],
  ['SGP', 'SG', 'southeast-asia', 'Singapore'],
  ['THA', 'TH', 'southeast-asia', 'Thailand'],
  ['TLS', 'TL', 'southeast-asia', 'Timor-Leste'],
  ['VNM', 'VN', 'southeast-asia', 'Vietnam'],
  ['BWA', 'BW', 'southern-africa', 'Botswana'],
  ['LSO', 'LS', 'southern-africa', 'Lesotho'],
  ['NAM', 'NA', 'southern-africa', 'Namibia'],
  ['SWZ', 'SZ', 'southern-africa', 'eSwatini'],
  ['ZAF', 'ZA', 'southern-africa', 'South Africa'],
  ['ALB', 'AL', 'southern-europe', 'Albania'],
  ['AND', 'AD', 'southern-europe', 'Andorra'],
  ['BIH', 'BA', 'southern-europe', 'Bosnia and Herz.'],
  ['ESP', 'ES', 'southern-europe', 'Spain'],
  ['GIB', 'GI', 'southern-europe', 'Gibraltar'],
  ['GRC', 'GR', 'southern-europe', 'Greece'],
  ['HRV', 'HR', 'southern-europe', 'Croatia'],
  ['ITA', 'IT', 'southern-europe', 'Italy'],
  ['KOS', 'XK', 'southern-europe', 'Kosovo'],
  ['MKD', 'MK', 'southern-europe', 'North Macedonia'],
  ['MLT', 'MT', 'southern-europe', 'Malta'],
  ['MNE', 'ME', 'southern-europe', 'Montenegro'],
  ['PRT', 'PT', 'southern-europe', 'Portugal'],
  ['SMR', 'SM', 'southern-europe', 'San Marino'],
  ['SRB', 'RS', 'southern-europe', 'Serbia'],
  ['SVN', 'SI', 'southern-europe', 'Slovenia'],
  ['VAT', 'VA', 'southern-europe', 'Vatican'],
  ['BMU', 'BM', 'usa-canada', 'Bermuda'],
  ['CAN', 'CA', 'usa-canada', 'Canada'],
  ['GRL', 'GL', 'usa-canada', 'Greenland'],
  ['SPM', 'PM', 'usa-canada', 'St. Pierre and Miquelon'],
  ['USA', 'US', 'usa-canada', 'United States of America'],
  ['BEN', 'BJ', 'west-africa', 'Benin'],
  ['BFA', 'BF', 'west-africa', 'Burkina Faso'],
  ['CIV', 'CI', 'west-africa', 'Côte d\'Ivoire'],
  ['CPV', 'CV', 'west-africa', 'Cabo Verde'],
  ['GHA', 'GH', 'west-africa', 'Ghana'],
  ['GIN', 'GN', 'west-africa', 'Guinea'],
  ['GMB', 'GM', 'west-africa', 'Gambia'],
  ['GNB', 'GW', 'west-africa', 'Guinea-Bissau'],
  ['LBR', 'LR', 'west-africa', 'Liberia'],
  ['MLI', 'ML', 'west-africa', 'Mali'],
  ['MRT', 'MR', 'west-africa', 'Mauritania'],
  ['NER', 'NE', 'west-africa', 'Niger'],
  ['NGA', 'NG', 'west-africa', 'Nigeria'],
  ['SEN', 'SN', 'west-africa', 'Senegal'],
  ['SLE', 'SL', 'west-africa', 'Sierra Leone'],
  ['TGO', 'TG', 'west-africa', 'Togo'],
  ['ARE', 'AE', 'west-asia', 'United Arab Emirates'],
  ['ARM', 'AM', 'west-asia', 'Armenia'],
  ['AZE', 'AZ', 'west-asia', 'Azerbaijan'],
  ['BHR', 'BH', 'west-asia', 'Bahrain'],
  ['CNM', '', 'west-asia', 'Cyprus U.N. Buffer Zone'],
  ['CYN', '', 'west-asia', 'N. Cyprus'],
  ['CYP', 'CY', 'west-asia', 'Cyprus'],
  ['ESB', '', 'west-asia', 'Dhekelia'],
  ['GEO', 'GE', 'west-asia', 'Georgia'],
  ['IRQ', 'IQ', 'west-asia', 'Iraq'],
  ['ISR', 'IL', 'west-asia', 'Israel'],
  ['JOR', 'JO', 'west-asia', 'Jordan'],
  ['KWT', 'KW', 'west-asia', 'Kuwait'],
  ['LBN', 'LB', 'west-asia', 'Lebanon'],
  ['OMN', 'OM', 'west-asia', 'Oman'],
  ['PSX', 'PS', 'west-asia', 'Palestine'],
  ['QAT', 'QA', 'west-asia', 'Qatar'],
  ['SAU', 'SA', 'west-asia', 'Saudi Arabia'],
  ['SYR', 'SY', 'west-asia', 'Syria'],
  ['TUR', 'TR', 'west-asia', 'Turkey'],
  ['WSB', '', 'west-asia', 'Akrotiri'],
  ['YEM', 'YE', 'west-asia', 'Yemen'],
  ['AUT', 'AT', 'western-europe', 'Austria'],
  ['BEL', 'BE', 'western-europe', 'Belgium'],
  ['CHE', 'CH', 'western-europe', 'Switzerland'],
  ['DEU', 'DE', 'western-europe', 'Germany'],
  ['FRA', 'FR', 'western-europe', 'France'],
  ['LIE', 'LI', 'western-europe', 'Liechtenstein'],
  ['LUX', 'LU', 'western-europe', 'Luxembourg'],
  ['MCO', 'MC', 'western-europe', 'Monaco'],
  ['NLD', 'NL', 'western-europe', 'Netherlands'],
];

/** ISO alpha-3 codes where Natural Earth's adm0_a3 differs. */
const ISO_ALIASES: Record<string, string> = { SSD: 'SDS', PSE: 'PSX', ESH: 'SAH', ALA: 'ALD', XKX: 'KOS' };

const BY_CODE = new Map<string, { region: string; name: string }>();
for (const [alpha3, alpha2, region, name] of COUNTRY_REGIONS) {
  BY_CODE.set(alpha3, { region, name });
  if (alpha2) BY_CODE.set(alpha2, { region, name });
}
for (const [iso, naturalEarth] of Object.entries(ISO_ALIASES)) BY_CODE.set(iso, BY_CODE.get(naturalEarth)!);

/** The region key for an ISO alpha-3 or alpha-2 country code (or a Natural Earth adm0_a3), or null when unknown. */
export function regionOfCountry(code: string): string | null {
  return BY_CODE.get(code.toUpperCase())?.region ?? null;
}

/** A country's short name (Natural Earth, e.g. 'Dem. Rep. Congo'), or null when unknown. */
export function countryName(code: string): string | null {
  return BY_CODE.get(code.toUpperCase())?.name ?? null;
}

/** `?place=continent:africa` plays that continent. Older country links play the country's continent. */
export function continentOf(key: string | null): ContinentKey | null {
  if (!key) return null;
  const [kind, value = ''] = key.split(':');
  if (kind === 'continent' && value in CONTINENT_NAMES) return value as ContinentKey;
  if (kind === 'country') {
    const region = regionOfCountry(value);
    return region ? REGIONS[region].continent : null;
  }
  return null;
}
